
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects grids that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.u
set test_file test.5

# The variable test_equation is the equation to test.

set test_equation {g\[1:4:9\]}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int32 i\\\[20\\\];
    Int32 j;
    String s;
    Grid {
     ARRAY:
        Float64 val\\\[length = 5\\\]\\\[width = 6\\\]\\\[height = 7\\\];
     MAPS:
        Float64 length\\\[5\\\];
        Float64 width\\\[6\\\];
        Float64 height\\\[7\\\];
    } g;
} test1;
Error: *"

expr-test_start p ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.u.exp,v $
# Revision 1.3  2003/04/22 19:40:30  jimg
# Merged with 3.3.1.
#
# Revision 1.2.2.1  2003/04/18 04:11:53  jimg
# Updated for the new version of test.5.
#
# Revision 1.2  2003/01/10 19:46:43  jimg
# Merged with code tagged release-3-2-10 on the release-3-2 branch. In many
# cases files were added on that branch (so they appear on the trunk for
# the first time).
#
# Revision 1.1.2.2  2002/06/12 00:03:34  jimg
# Added Comment.
#
# Revision 1.1.2.1  2002/06/12 00:00:39  jimg
# Added.
