
# expect/tcl code to test the expression parser and scanner
# jhrg
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir
global skip_empty_sequence_tests

# The variable `test_file' is the name of the das input file for this test.

set test_name test.g
set test_file test.4

# The variable test_equation is the equation to test.

set test_equation {"s&s=~\"Very\""}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int32 i\[20\];
    String s;
    Int32 j;
    List Int32 l;
} test1;
The data:"

if {$skip_empty_sequence_tests != 1} {
expr-test_start p ${srcdir}/${test_file} ${test_equation}

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    xfail "$test_name"
}
}

expr-test_start P ${srcdir}/${test_file} ${test_equation}

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    xfail "$test_name"
}


