
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "common_tests.exp"

expr-test_start w ${srcdir}/test.c1 "geogrid(SST,-82,61,-19,38)"

compare_stdout ${srcdir}/data.z3 "test.z3.exp: latitude reversed"
