
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "common_tests.exp"

expr-test_start w ${srcdir}/test.61 "i\\\[1:2\\\]\\\[1:2\\\]"

compare_stdout ${srcdir}/data.61d "test.61d.exp: constrained two dim array"

expr-test_start W ${srcdir}/test.61 "i\\\[1:2\\\]\\\[1:2\\\]"

compare_stdout ${srcdir}/data.61d "test.61d.exp: constrained two dim array"
