
# expect/tcl code to test the expression parser and scanner
# jhrg

source common_tests.exp

global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.s
set test_file test.8

# The variable test_equation is the equation to test.

set test_equation {"data%20name,y"}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int16 x%23y;
    UInt16 y;
    Int32 data%23i\[20\]\[10\];
    Float64 data%20name\[10\];
} data8;
The data:
UInt16 y = 64000;
Float64 data%20name\[10\] = {99.999, 99.999, 99.999, 99.999, 99.999, 99.999, 99.999, 99.999, 99.999, 99.999};
"

expr-test_start p ${srcdir}/${test_file} ${test_equation} 

compare_stdout $test_out "projection with `%20' in id name."

expr-test_start P ${srcdir}/${test_file} ${test_equation} 

compare_stdout $test_out "projection with `%20' in id name."


