
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.v
set test_file test.6

# The variable test_equation is the equation to test.

set test_equation {i\[1:4:9\]}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int32 i\\\[20\\\]\\\[10\\\];
    String s;
} test1;
Error: *"

expr-test_start P ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.v.exp,v $
# Revision 1.2  2003/01/10 19:46:43  jimg
# Merged with code tagged release-3-2-10 on the release-3-2 branch. In many
# cases files were added on that branch (so they appear on the trunk for
# the first time).
#
# Revision 1.1.2.2  2002/06/12 00:02:12  jimg
# Added comment.
#
# Revision 1.1.2.1  2002/06/12 00:00:39  jimg
# Added.
#
