
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "common_tests.exp"

expr-test_start w ${srcdir}/test.c4 "geogrid(SST,61,-82,38,-19,\"time=1024\")"

compare_stdout ${srcdir}/data.z7 "test.z7.exp: Three dimensions, Longitude rightmost"

expr-test_start W ${srcdir}/test.c4 "geogrid(SST,61,-82,38,-19,\"time=1024\")"

compare_stdout ${srcdir}/data.z7 "test.z7.exp: Three dimensions, Longitude rightmost"
