
# expect/tcl code to test the expression parser and scanner
# jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.q
set test_file test.7

# The variable test_equation is the equation to test.

set test_equation {x,y,f}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int16 x;
    UInt16 y;
    Float32 f;
} data5;
The data:
Int16 x = 32000;
UInt16 y = 64000;
Float32 f = 99.999;"

expr-test_start p ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

expr-test_start P ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


