
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

source "common_tests.exp"

expr-test_start W ${srcdir}/test.c0 "geogrid(SST)"

compare_stdout ${srcdir}/data.z0 "test.z0.exp: Bad args"
