#
# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Id$

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.20

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "DDS past semantic check
DDS past full semantic check
Dataset {
    Int32 a;
    Grid {
     ARRAY:
        Byte Image%23data\[size*10 = 512\];
     MAPS:
        String colors\[size*10 = 512\];
    } huh;
} test.20;"

dds-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.20.exp,v $
# Revision 1.2  2003/01/10 19:46:43  jimg
# Merged with code tagged release-3-2-10 on the release-3-2 branch. In many
# cases files were added on that branch (so they appear on the trunk for
# the first time).
#
# Revision 1.1.2.2  2002/06/11 00:39:01  jimg
# Fixed...
#
# Revision 1.1.2.1  2002/06/11 00:38:06  jimg
# Added
#
