# Consider using https://pre-commit.ci/
# jhrg 7/14/24
#
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Let clang-format handle this because otherwise test baselines will get hacked. jhrg 7/14/24
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i, "*.cc", "*.h", "d4_ce/*.cc", "d4_ce/*.h", "d4_function/*.cc", "d4_function/*.h"]
      # - id: clang-tidy
