fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [*.cc *.h d4_ce/*.cc d4_ce/*.h d4_function/*.cc d4_function/*.h]
      # - id: clang-tidy
