Attributes {
    HDF_GLOBAL {
    }
    CoreMetadata {
        OrbitNumber {
            Int32 Value -9999;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
        RangeBeginningDate {
            String Value 1998/09/09;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
    }
    percipitate {
        String name "dim_0_scan";
    }
    percipitate {
        String name "dim_1_longitude";
    }
    percipitate {
        String name "dim_2_latitude";
    }
    relError {
        String name "dim_0_scan";
    }
    relError {
        String name "dim_1_longitude";
    }
    relError {
        String name "dim_2_latitude";
    }
}
