Attributes {
    WVC_Lat {
        String long_name "latitude";
        String units "deg";
        Float64 scale_factor 0.01;
        Float64 scale_factor_err 0;
        Float64 add_offset 0;
        Float64 add_offset_err 0;
        Int32 calibrated_nt 22;
        Int16 valid_range -9000, 7771;
    }
    WVC_Lat_dim_0 {
        String name "row";
        String long_name "WVC row";
    }
    WVC_Lat_dim_1 {
        String name "WVC";
        String long_name "WVC index";
    }
}
