The complete DDS:
Dataset {
    Grid {
      Array:
        Byte SST[lat_reversed = 13][lon = 11];
      Maps:
        Float32 lat_reversed[13];
        Float32 lon[11];
    } SST;
} SST_grid;
The data:
Grid {
  Array:
    Byte SST[lat_reversed = 4][lon = 2];
  Maps:
    Float32 lat_reversed[4];
    Float32 lon[2];
} SST = {  Array: {{0, 1},{2, 3},{4, 5},{6, 7}}  Maps: {28, 41, 54, 67}, {-51, -19} };
