Attributes {
    NSCAT%20Rev%2020 {
        WVC_Lat {
            String long_name "latitude";
            String units "deg";
            Float64 scale_factor 0.01;
            Float64 scale_factor_err 0;
            Float64 add_offset 0;
            Float64 add_offset_err 0;
            Int32 calibrated_nt 22;
            Int16 valid_range -9000, 7771;
        }
    }
    HDF_GLOBAL {
        String Producer_Agency "OPeNDAP\\000";
        String Producer_Institution "OPENDAP\\000";
        String Sensor_Name "TESTS\\000";
        String Project_ID "TESTS\\000";
    }
}
