#!/bin/sh
#
# Check to make sure the computer is running 10.3 or later.

version=`uname -a | sed 's/.*Darwin Kernel Version \([0-9.]*\):.*/\1/'`
major=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\1/'`
minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`

if test $major -lt 7 -o $major -eq 7 -a $minor -lt 9
then
    # Warn and display message 16
    exit 48
fi

exit 0
