Attributes {
    HDF_GLOBAL {
    }
    CoreMetadata {
        OrbitNumber {
            Int32 Value -9999;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
        RangeBeginningDate {
            String Value 1998/09/09;
            String Data_Location PGE;
            String Mandatory FALSE;
        }
    }
    percipitate_dim_0 {
        String name "scan";
    }
    percipitate_dim_1 {
        String name "longitude";
    }
    percipitate_dim_2 {
        String name "latitude";
    }
    relError_dim_0 {
        String name "scan";
    }
    relError_dim_1 {
        String name "longitude";
    }
    relError_dim_2 {
        String name "latitude";
    }
}
