
# expect/tcl code to test the das scanner
# jhrg
#
# $Log: scanner.9.exp,v $
# Revision 1.1  1996/07/16 16:54:40  jimg
# Added.
#
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

set test_name scanner.9

set prompt "das-test:"
set timeout 2
set pass 1

das-test_start s

expect {
    "${prompt} " { 
    }
    timeout { 
	send_user "Timeout\n"
	set pass 0
    }
}

if {$pass} {
    set thing "url\r\n"
    send $thing

    expect {
	-re ".*URL\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    set thing "Url\r\n"
    send $thing

    expect {
	-re ".*URL\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    set thing "URL\r\n"
    send $thing

    expect {
	-re ".*URL\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    pass $test_name
} else {
    fail $test_name
}

das-test_exit
