# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.5.exp,v $
# Revision 1.7  2003/12/11 01:08:38  jimg
# More fixes after resolving conflicts. This code still fails some tests.
#
# Revision 1.6.10.1  2003/10/03 16:26:30  jimg
# Fixed tests; I changed the text of das-test just a little and so these
# had to be updated. I wanted to be sure that the error message was from
# an exception and not just a write to stderr.
#
# Revision 1.6  2000/06/16 18:15:01  jimg
# Merged with 3.1.7
#
# Revision 1.5.38.1  2000/06/15 02:24:57  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.5  1997/05/13 23:29:27  jimg
# *** empty log message ***
#
# Revision 1.4  1996/05/14 15:40:52  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.3  1994/12/09  21:45:50  jimg
# Modified for new unix.exp.
#
# Revision 1.2  1994/09/09  16:15:25  jimg
# Fixed namign of the test (was given as $srcdir//$test_name, should have been
# $srcdir$test_name).
#
# Revision 1.1  1994/08/29  19:57:23  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.5

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Caught Error object:
Error scanning DAS object text: Unterminated quote (starts on line 6)
"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


