# expect/tcl code to test the das parser and scanner
# jhrg
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.1

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    var1 {
        String name \"bob\";
        String type \"human\";
        Int32 age 19;
    }
    var2 {
        String name \"joe\";
        String type \"dog\";
        Int32 age 8;
    }
    var3 {
        Int32 size 8;
        String color \"red\";
        String type \"art\";
    }
    var4 {
    }
    var5 {
        String height \"5.0in.\";
        String units \"inches\";
        Float64 max 5.0;
        String weight \"100lbs\";
        String color \"red\";
    }
}"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


