# expect/tcl code to test the das parser and scanner
# jhrg
#


global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.3

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    var1 {
        String comment \"One thing about these long comments is that they
might cause problems with memory - overwrites, ...\";
        String comment2 \"This quote tests a \\\"quote within a quote\\\", he said\";
        String quote1 \"\\\"\";
        String quote2 \"\\7 seven\";
    }
}"

das-test_start p $srcdir/$test_name

# send_user "comp output: $comp_output\n"
# send_user "test out: $test_out\n"

# send_user "result of compare [string compare $test_out $comp_output]\n"
# send_user "result of match [string match $test_out $comp_output]\n"

if ![string compare $test_out $comp_output] {
    pass "$test_name"
} else {
    fail "$test_name"
}


