
# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.29.exp,v $
# Revision 1.3  2003/12/11 01:08:38  jimg
# More fixes after resolving conflicts. This code still fails some tests.
#
# Revision 1.2.6.1  2003/10/03 16:26:30  jimg
# Fixed tests; I changed the text of das-test just a little and so these
# had to be updated. I wanted to be sure that the error message was from
# an exception and not just a write to stderr.
#
# Revision 1.2  2001/01/26 19:48:10  jimg
# Merged with release-3-2-3.
#
# Revision 1.1.2.1  2000/11/30 05:20:20  jimg
# Added
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.29

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Caught Error object:
Error parsing the text on line 15
Could not find the attribute `var1.comp' in the attribute object.
"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
