Attributes {
    ClrOLR_A {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_A";
        String fullnamepath "/ClrOLR_A";
    }
    GPHeight_MW_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_A_sdev";
        String fullnamepath "/GPHeight_MW_A_sdev";
    }
    CO_VMR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CO_VMR_TqJ_D_ct";
        String fullnamepath "/CO_VMR_TqJ_D_ct";
    }
    RelHum_liquid_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_A_max";
        String fullnamepath "/RelHum_liquid_A_max";
    }
    Temperature_A_err {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_A_err";
        String fullnamepath "/Temperature_A_err";
    }
    TotH2OVap_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_A";
        String fullnamepath "/TotH2OVap_TqJ_A";
    }
    TotCldLiqH2O_MW_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_A_min";
        String fullnamepath "/TotCldLiqH2O_MW_A_min";
    }
    RelHum_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_A_min";
        String fullnamepath "/RelHum_A_min";
    }
    TropHeight_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TropHeight_TqJ_D_ct";
        String fullnamepath "/TropHeight_TqJ_D_ct";
    }
    TropHeight_D_ct {
        Int16 _FillValue 0;
        String origname "TropHeight_D_ct";
        String fullnamepath "/TropHeight_D_ct";
    }
    O3_VMR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_D";
        String fullnamepath "/O3_VMR_TqJ_D";
    }
    SurfPres_Forecast_D_ct {
        Int16 _FillValue 0;
        String origname "SurfPres_Forecast_D_ct";
        String fullnamepath "/SurfPres_Forecast_D_ct";
    }
    CloudFrc_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_A_sdev";
        String fullnamepath "/CloudFrc_A_sdev";
    }
    RelHum_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_D_max";
        String fullnamepath "/RelHum_TqJ_D_max";
    }
    CoarseCloudPres_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_D_sdev";
        String fullnamepath "/CoarseCloudPres_TqJ_D_sdev";
    }
    CloudFrc_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_D_max";
        String fullnamepath "/CloudFrc_TqJ_D_max";
    }
    RelHumSurf_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_TqJ_D_ct";
        String fullnamepath "/RelHumSurf_TqJ_D_ct";
    }
    O3_VMR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_A_max";
        String fullnamepath "/O3_VMR_TqJ_A_max";
    }
    CloudTopPres_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_D_min";
        String fullnamepath "/CloudTopPres_TqJ_D_min";
    }
    Emis_MW_D {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_D";
        String fullnamepath "/Emis_MW_D";
    }
    CloudTopPres_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_A";
        String fullnamepath "/CloudTopPres_A";
    }
    SurfSkinTemp_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_D";
        String fullnamepath "/SurfSkinTemp_TqJ_D";
    }
    CloudFrc_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_A_err";
        String fullnamepath "/CloudFrc_TqJ_A_err";
    }
    H2O_MMR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_D";
        String fullnamepath "/H2O_MMR_TqJ_D";
    }
    TotCO_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TotCO_TqJ_A_ct";
        String fullnamepath "/TotCO_TqJ_A_ct";
    }
    TropPres_D_ct {
        Int16 _FillValue 0;
        String origname "TropPres_D_ct";
        String fullnamepath "/TropPres_D_ct";
    }
    FineCloudFrc_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_A_sdev";
        String fullnamepath "/FineCloudFrc_TqJ_A_sdev";
    }
    TotCO_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_D_max";
        String fullnamepath "/TotCO_TqJ_D_max";
    }
    ClrOLR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_A";
        String fullnamepath "/ClrOLR_TqJ_A";
    }
    TotCldLiqH2O_MW_A_err {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_A_err";
        String fullnamepath "/TotCldLiqH2O_MW_A_err";
    }
    H2O_MMR_Surf_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_D_min";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D_min";
    }
    Temperature_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "Temperature_TqJ_D_ct";
        String fullnamepath "/Temperature_TqJ_D_ct";
    }
    TotCH4_A_ct {
        Int16 _FillValue 0;
        String origname "TotCH4_A_ct";
        String fullnamepath "/TotCH4_A_ct";
    }
    H2O_MMR_Lyr_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_A_min";
        String fullnamepath "/H2O_MMR_Lyr_A_min";
    }
    CO_VMR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_D_sdev";
        String fullnamepath "/CO_VMR_TqJ_D_sdev";
    }
    H2O_MMR_Surf_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_D_err";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D_err";
    }
    Temperature_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_D";
        String fullnamepath "/Temperature_TqJ_D";
    }
    CloudFrc_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_D_err";
        String fullnamepath "/CloudFrc_TqJ_D_err";
    }
    RelHum_A_ct {
        Int16 _FillValue 0;
        String origname "RelHum_A_ct";
        String fullnamepath "/RelHum_A_ct";
    }
    RelHumSurf_liquid_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_liquid_TqJ_A_ct";
        String fullnamepath "/RelHumSurf_liquid_TqJ_A_ct";
    }
    H2O_MMR_Lyr_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_D_sdev";
        String fullnamepath "/H2O_MMR_Lyr_D_sdev";
    }
    EmisIR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_A_sdev";
        String fullnamepath "/EmisIR_A_sdev";
    }
    TropTemp_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_A_sdev";
        String fullnamepath "/TropTemp_A_sdev";
    }
    TropPres_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_D_sdev";
        String fullnamepath "/TropPres_D_sdev";
    }
    OLR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "OLR_D_err";
        String fullnamepath "/OLR_D_err";
    }
    O3_VMR_D {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_D";
        String fullnamepath "/O3_VMR_D";
    }
    H2O_MMR_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_D_ct";
        String fullnamepath "/H2O_MMR_D_ct";
    }
    GPHeight_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_D";
        String fullnamepath "/GPHeight_TqJ_D";
    }
    SurfSkinTemp_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_A_err";
        String fullnamepath "/SurfSkinTemp_TqJ_A_err";
    }
    TropTemp_D_ct {
        Int16 _FillValue 0;
        String origname "TropTemp_D_ct";
        String fullnamepath "/TropTemp_D_ct";
    }
    Temperature_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_A_min";
        String fullnamepath "/Temperature_TqJ_A_min";
    }
    TotH2OVap_A_err {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_A_err";
        String fullnamepath "/TotH2OVap_A_err";
    }
    Temperature_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_D_err";
        String fullnamepath "/Temperature_TqJ_D_err";
    }
    OLR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_D_min";
        String fullnamepath "/OLR_TqJ_D_min";
    }
    SurfSkinTemp_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_D_max";
        String fullnamepath "/SurfSkinTemp_TqJ_D_max";
    }
    SurfSkinTemp_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_A";
        String fullnamepath "/SurfSkinTemp_TqJ_A";
    }
    CloudTopPres_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_D_sdev";
        String fullnamepath "/CloudTopPres_D_sdev";
    }
    SurfPres_Forecast_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_A";
        String fullnamepath "/SurfPres_Forecast_A";
    }
    H2O_MMR_Lyr_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_D_err";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D_err";
    }
    CoarseCloudTemp_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_A";
        String fullnamepath "/CoarseCloudTemp_TqJ_A";
    }
    CH4_VMR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_D_min";
        String fullnamepath "/CH4_VMR_TqJ_D_min";
    }
    RelHum_liquid_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "RelHum_liquid_TqJ_A_ct";
        String fullnamepath "/RelHum_liquid_TqJ_A_ct";
    }
    TropHeight_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_A_min";
        String fullnamepath "/TropHeight_TqJ_A_min";
    }
    H2O_MMR_Lyr_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Lyr_TqJ_A_ct";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A_ct";
    }
    TotalCounts_TqJ_A {
        Int16 _FillValue 0;
        String origname "TotalCounts_TqJ_A";
        String fullnamepath "/TotalCounts_TqJ_A";
    }
    OLR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "OLR_A_max";
        String fullnamepath "/OLR_A_max";
    }
    TropPres_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_A_max";
        String fullnamepath "/TropPres_TqJ_A_max";
    }
    TotO3_D {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_D";
        String fullnamepath "/TotO3_D";
    }
    CoarseCloudTemp_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudTemp_D_ct";
        String fullnamepath "/CoarseCloudTemp_D_ct";
    }
    TropHeight_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_D_min";
        String fullnamepath "/TropHeight_D_min";
    }
    TotH2OVap_D_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_D_ct";
        String fullnamepath "/TotH2OVap_D_ct";
    }
    FineCloudFrc_D_max {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_D_max";
        String fullnamepath "/FineCloudFrc_D_max";
    }
    O3_VMR_A_ct {
        Int16 _FillValue 0;
        String origname "O3_VMR_A_ct";
        String fullnamepath "/O3_VMR_A_ct";
    }
    GPHeight_MW_A_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_A_max";
        String fullnamepath "/GPHeight_MW_A_max";
    }
    CO_VMR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_A_max";
        String fullnamepath "/CO_VMR_TqJ_A_max";
    }
    CloudTopPres_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CloudTopPres_TqJ_A_ct";
        String fullnamepath "/CloudTopPres_TqJ_A_ct";
    }
    H2O_MMR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_A";
        String fullnamepath "/H2O_MMR_TqJ_A";
    }
    EmisIR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_A_sdev";
        String fullnamepath "/EmisIR_TqJ_A_sdev";
    }
    TotH2OVap_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_D_err";
        String fullnamepath "/TotH2OVap_TqJ_D_err";
    }
    TotalCounts_A {
        Int16 _FillValue 0;
        String origname "TotalCounts_A";
        String fullnamepath "/TotalCounts_A";
    }
    O3_VMR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_A_sdev";
        String fullnamepath "/O3_VMR_A_sdev";
    }
    GPHeight_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_D_max";
        String fullnamepath "/GPHeight_TqJ_D_max";
    }
    O3_VMR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_D_sdev";
        String fullnamepath "/O3_VMR_D_sdev";
    }
    CH4_VMR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_D_max";
        String fullnamepath "/CH4_VMR_TqJ_D_max";
    }
    CloudTopTemp_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_A_sdev";
        String fullnamepath "/CloudTopTemp_TqJ_A_sdev";
    }
    TotH2OVap_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_TqJ_A_ct";
        String fullnamepath "/TotH2OVap_TqJ_A_ct";
    }
    CloudTopTemp_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_D_min";
        String fullnamepath "/CloudTopTemp_TqJ_D_min";
    }
    TotCH4_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_D_min";
        String fullnamepath "/TotCH4_D_min";
    }
    CoarseCloudPres_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudPres_TqJ_D_ct";
        String fullnamepath "/CoarseCloudPres_TqJ_D_ct";
    }
    TotH2OVap_MW_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_A_sdev";
        String fullnamepath "/TotH2OVap_MW_A_sdev";
    }
    CoarseCloudFrc_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_D";
        String fullnamepath "/CoarseCloudFrc_TqJ_D";
    }
    CloudFrc_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_D_min";
        String fullnamepath "/CloudFrc_TqJ_D_min";
    }
    RelHumSurf_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_TqJ_A_ct";
        String fullnamepath "/RelHumSurf_TqJ_A_ct";
    }
    CloudFrc_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CloudFrc_TqJ_D_ct";
        String fullnamepath "/CloudFrc_TqJ_D_ct";
    }
    CoarseCloudTemp_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_D";
        String fullnamepath "/CoarseCloudTemp_D";
    }
    TropPres_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_A_min";
        String fullnamepath "/TropPres_A_min";
    }
    RelHum_liquid_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_D_max";
        String fullnamepath "/RelHum_liquid_TqJ_D_max";
    }
    FineCloudFrc_A_min {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_A_min";
        String fullnamepath "/FineCloudFrc_A_min";
    }
    ClrOLR_D {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_D";
        String fullnamepath "/ClrOLR_D";
    }
    H2O_MMR_Surf_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_A";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A";
    }
    O3_VMR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_A_min";
        String fullnamepath "/O3_VMR_A_min";
    }
    CloudTopTemp_D_ct {
        Int16 _FillValue 0;
        String origname "CloudTopTemp_D_ct";
        String fullnamepath "/CloudTopTemp_D_ct";
    }
    FineCloudFrc_A_max {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_A_max";
        String fullnamepath "/FineCloudFrc_A_max";
    }
    FineCloudFrc_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_A_sdev";
        String fullnamepath "/FineCloudFrc_A_sdev";
    }
    CloudTopTemp_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_A_err";
        String fullnamepath "/CloudTopTemp_A_err";
    }
    RelHumSurf_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_A_sdev";
        String fullnamepath "/RelHumSurf_A_sdev";
    }
    CloudFrc_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_A";
        String fullnamepath "/CloudFrc_TqJ_A";
    }
    CO_VMR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_A_min";
        String fullnamepath "/CO_VMR_A_min";
    }
    SurfAirTemp_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_D_sdev";
        String fullnamepath "/SurfAirTemp_TqJ_D_sdev";
    }
    FineCloudFrc_D_ct {
        Int16 _FillValue 0;
        String origname "FineCloudFrc_D_ct";
        String fullnamepath "/FineCloudFrc_D_ct";
    }
    TotCH4_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_D_min";
        String fullnamepath "/TotCH4_TqJ_D_min";
    }
    TropTemp_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_A_max";
        String fullnamepath "/TropTemp_TqJ_A_max";
    }
    RelHumSurf_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_A_max";
        String fullnamepath "/RelHumSurf_A_max";
    }
    Temperature_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_D_sdev";
        String fullnamepath "/Temperature_TqJ_D_sdev";
    }
    TotCH4_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TotCH4_TqJ_D_ct";
        String fullnamepath "/TotCH4_TqJ_D_ct";
    }
    H2O_MMR_Surf_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_D_min";
        String fullnamepath "/H2O_MMR_Surf_D_min";
    }
    EmisIR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_D_err";
        String fullnamepath "/EmisIR_TqJ_D_err";
    }
    H2O_MMR_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_A";
        String fullnamepath "/H2O_MMR_A";
    }
    O3_VMR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_D_min";
        String fullnamepath "/O3_VMR_D_min";
    }
    Temperature_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "Temperature_TqJ_A_ct";
        String fullnamepath "/Temperature_TqJ_A_ct";
    }
    CO_VMR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_D_max";
        String fullnamepath "/CO_VMR_D_max";
    }
    TropTemp_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_D_max";
        String fullnamepath "/TropTemp_TqJ_D_max";
    }
    CloudTopPres_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_D";
        String fullnamepath "/CloudTopPres_D";
    }
    TropPres_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TropPres_TqJ_D_ct";
        String fullnamepath "/TropPres_TqJ_D_ct";
    }
    CloudTopPres_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_A_err";
        String fullnamepath "/CloudTopPres_A_err";
    }
    CloudTopPres_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_A_err";
        String fullnamepath "/CloudTopPres_TqJ_A_err";
    }
    CloudTopPres_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_A_min";
        String fullnamepath "/CloudTopPres_TqJ_A_min";
    }
    CloudTopPres_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_D_err";
        String fullnamepath "/CloudTopPres_D_err";
    }
    CloudTopPres_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_D_min";
        String fullnamepath "/CloudTopPres_D_min";
    }
    TotH2OVap_MW_A_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_MW_A_ct";
        String fullnamepath "/TotH2OVap_MW_A_ct";
    }
    O3_VMR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "O3_VMR_TqJ_A_ct";
        String fullnamepath "/O3_VMR_TqJ_A_ct";
    }
    TotO3_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_D_err";
        String fullnamepath "/TotO3_TqJ_D_err";
    }
    H2O_MMR_Surf_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_D";
        String fullnamepath "/H2O_MMR_Surf_D";
    }
    TropTemp_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_D_min";
        String fullnamepath "/TropTemp_D_min";
    }
    CH4_VMR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_D";
        String fullnamepath "/CH4_VMR_TqJ_D";
    }
    RelHumSurf_liquid_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_D_max";
        String fullnamepath "/RelHumSurf_liquid_TqJ_D_max";
    }
    Emis_MW_A_ct {
        Int16 _FillValue 0;
        String origname "Emis_MW_A_ct";
        String fullnamepath "/Emis_MW_A_ct";
    }
    EmisIR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_A_min";
        String fullnamepath "/EmisIR_TqJ_A_min";
    }
    CH4_VMR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CH4_VMR_TqJ_D_ct";
        String fullnamepath "/CH4_VMR_TqJ_D_ct";
    }
    TotO3_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_D";
        String fullnamepath "/TotO3_TqJ_D";
    }
    RelHum_liquid_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_D";
        String fullnamepath "/RelHum_liquid_TqJ_D";
    }
    TotCH4_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_A_max";
        String fullnamepath "/TotCH4_TqJ_A_max";
    }
    GPHeight_A_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_A_max";
        String fullnamepath "/GPHeight_A_max";
    }
    O3_VMR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_D_max";
        String fullnamepath "/O3_VMR_D_max";
    }
    SurfAirTemp_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_A_max";
        String fullnamepath "/SurfAirTemp_A_max";
    }
    Temperature_A_ct {
        Int16 _FillValue 0;
        String origname "Temperature_A_ct";
        String fullnamepath "/Temperature_A_ct";
    }
    H2O_MMR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_A_min";
        String fullnamepath "/H2O_MMR_TqJ_A_min";
    }
    SurfSkinTemp_D_ct {
        Int16 _FillValue 0;
        String origname "SurfSkinTemp_D_ct";
        String fullnamepath "/SurfSkinTemp_D_ct";
    }
    O3_VMR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_A_err";
        String fullnamepath "/O3_VMR_TqJ_A_err";
    }
    EmisIR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_D_err";
        String fullnamepath "/EmisIR_D_err";
    }
    Temperature_A_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_A_max";
        String fullnamepath "/Temperature_A_max";
    }
    RelHumSurf_liquid_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_D_min";
        String fullnamepath "/RelHumSurf_liquid_TqJ_D_min";
    }
    ClrOLR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_D_sdev";
        String fullnamepath "/ClrOLR_TqJ_D_sdev";
    }
    EmisIR_A_ct {
        Int16 _FillValue 0;
        String origname "EmisIR_A_ct";
        String fullnamepath "/EmisIR_A_ct";
    }
    OLR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_D";
        String fullnamepath "/OLR_TqJ_D";
    }
    Temperature_MW_A {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_A";
        String fullnamepath "/Temperature_MW_A";
    }
    SurfAirTemp_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_A_sdev";
        String fullnamepath "/SurfAirTemp_TqJ_A_sdev";
    }
    CloudTopPres_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_D_sdev";
        String fullnamepath "/CloudTopPres_TqJ_D_sdev";
    }
    CloudTopTemp_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_A_err";
        String fullnamepath "/CloudTopTemp_TqJ_A_err";
    }
    TotCH4_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_A_sdev";
        String fullnamepath "/TotCH4_A_sdev";
    }
    EmisIR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_D_sdev";
        String fullnamepath "/EmisIR_TqJ_D_sdev";
    }
    RelHumSurf_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_D_max";
        String fullnamepath "/RelHumSurf_D_max";
    }
    SurfAirTemp_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_D_min";
        String fullnamepath "/SurfAirTemp_D_min";
    }
    FineCloudFrc_A {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_A";
        String fullnamepath "/FineCloudFrc_A";
    }
    SurfAirTemp_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_D_max";
        String fullnamepath "/SurfAirTemp_TqJ_D_max";
    }
    TropHeight_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_D_min";
        String fullnamepath "/TropHeight_TqJ_D_min";
    }
    H2O_MMR_Lyr_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_A_max";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A_max";
    }
    SurfSkinTemp_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "SurfSkinTemp_TqJ_D_ct";
        String fullnamepath "/SurfSkinTemp_TqJ_D_ct";
    }
    SurfAirTemp_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_A_err";
        String fullnamepath "/SurfAirTemp_TqJ_A_err";
    }
    ClrOLR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_A_err";
        String fullnamepath "/ClrOLR_A_err";
    }
    TropTemp_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_D_sdev";
        String fullnamepath "/TropTemp_D_sdev";
    }
    CloudTopTemp_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_D_min";
        String fullnamepath "/CloudTopTemp_D_min";
    }
    CoarseCloudPres_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_D";
        String fullnamepath "/CoarseCloudPres_D";
    }
    TropPres_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_D_min";
        String fullnamepath "/TropPres_D_min";
    }
    TotCO_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_A_sdev";
        String fullnamepath "/TotCO_TqJ_A_sdev";
    }
    H2O_MMR_Surf_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_A_sdev";
        String fullnamepath "/H2O_MMR_Surf_A_sdev";
    }
    TotH2OVap_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_A_sdev";
        String fullnamepath "/TotH2OVap_A_sdev";
    }
    TotCldLiqH2O_MW_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_D_max";
        String fullnamepath "/TotCldLiqH2O_MW_D_max";
    }
    CH4_VMR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_A_max";
        String fullnamepath "/CH4_VMR_A_max";
    }
    CH4_VMR_A {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_A";
        String fullnamepath "/CH4_VMR_A";
    }
    H2O_MMR_Surf_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_D_max";
        String fullnamepath "/H2O_MMR_Surf_D_max";
    }
    SurfSkinTemp_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_D_sdev";
        String fullnamepath "/SurfSkinTemp_TqJ_D_sdev";
    }
    OLR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "OLR_A_sdev";
        String fullnamepath "/OLR_A_sdev";
    }
    TotCO_D {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_D";
        String fullnamepath "/TotCO_D";
    }
    CoarseCloudFrc_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudFrc_TqJ_D_ct";
        String fullnamepath "/CoarseCloudFrc_TqJ_D_ct";
    }
    TotCH4_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_D_max";
        String fullnamepath "/TotCH4_D_max";
    }
    H2O_MMR_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_A_ct";
        String fullnamepath "/H2O_MMR_A_ct";
    }
    H2O_MMR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_TqJ_A_ct";
        String fullnamepath "/H2O_MMR_TqJ_A_ct";
    }
    SurfSkinTemp_A_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_A_err";
        String fullnamepath "/SurfSkinTemp_A_err";
    }
    SurfPres_Forecast_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_D_sdev";
        String fullnamepath "/SurfPres_Forecast_TqJ_D_sdev";
    }
    CO_VMR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_A_err";
        String fullnamepath "/CO_VMR_A_err";
    }
    TotH2OVap_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_D_min";
        String fullnamepath "/TotH2OVap_D_min";
    }
    Temperature_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_A";
        String fullnamepath "/Temperature_TqJ_A";
    }
    TotO3_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_D_max";
        String fullnamepath "/TotO3_TqJ_D_max";
    }
    SurfAirTemp_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_D_err";
        String fullnamepath "/SurfAirTemp_TqJ_D_err";
    }
    GPHeight_MW_D_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_D_min";
        String fullnamepath "/GPHeight_MW_D_min";
    }
    CO_VMR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_D_sdev";
        String fullnamepath "/CO_VMR_D_sdev";
    }
    RelHum_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_A_max";
        String fullnamepath "/RelHum_TqJ_A_max";
    }
    RelHumSurf_liquid_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_liquid_TqJ_D_ct";
        String fullnamepath "/RelHumSurf_liquid_TqJ_D_ct";
    }
    H2O_MMR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_A_sdev";
        String fullnamepath "/H2O_MMR_TqJ_A_sdev";
    }
    CH4_VMR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_D_sdev";
        String fullnamepath "/CH4_VMR_TqJ_D_sdev";
    }
    O3_VMR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_D_err";
        String fullnamepath "/O3_VMR_D_err";
    }
    TotO3_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_A_sdev";
        String fullnamepath "/TotO3_A_sdev";
    }
    OLR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_A_err";
        String fullnamepath "/OLR_TqJ_A_err";
    }
    CloudFrc_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_D";
        String fullnamepath "/CloudFrc_TqJ_D";
    }
    SurfAirTemp_A_ct {
        Int16 _FillValue 0;
        String origname "SurfAirTemp_A_ct";
        String fullnamepath "/SurfAirTemp_A_ct";
    }
    CoarseCloudFrc_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_A_sdev";
        String fullnamepath "/CoarseCloudFrc_TqJ_A_sdev";
    }
    RelHumSurf_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_D";
        String fullnamepath "/RelHumSurf_TqJ_D";
    }
    TotCH4_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_A_sdev";
        String fullnamepath "/TotCH4_TqJ_A_sdev";
    }
    CO_VMR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_A_sdev";
        String fullnamepath "/CO_VMR_TqJ_A_sdev";
    }
    H2O_MMR_Surf_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_A_err";
        String fullnamepath "/H2O_MMR_Surf_A_err";
    }
    RelHumSurf_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_A_max";
        String fullnamepath "/RelHumSurf_TqJ_A_max";
    }
    TotCH4_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_D_sdev";
        String fullnamepath "/TotCH4_D_sdev";
    }
    TotH2OVap_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_A_err";
        String fullnamepath "/TotH2OVap_TqJ_A_err";
    }
    GPHeight_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_D_min";
        String fullnamepath "/GPHeight_TqJ_D_min";
    }
    SurfSkinTemp_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_A_sdev";
        String fullnamepath "/SurfSkinTemp_A_sdev";
    }
    CO_VMR_D {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_D";
        String fullnamepath "/CO_VMR_D";
    }
    CloudTopTemp_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_D";
        String fullnamepath "/CloudTopTemp_TqJ_D";
    }
    TotO3_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_A_sdev";
        String fullnamepath "/TotO3_TqJ_A_sdev";
    }
    CoarseCloudFrc_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_D_min";
        String fullnamepath "/CoarseCloudFrc_TqJ_D_min";
    }
    TropPres_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_D";
        String fullnamepath "/TropPres_TqJ_D";
    }
    RelHum_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "RelHum_TqJ_A_ct";
        String fullnamepath "/RelHum_TqJ_A_ct";
    }
    Temperature_MW_D_ct {
        Int16 _FillValue 0;
        String origname "Temperature_MW_D_ct";
        String fullnamepath "/Temperature_MW_D_ct";
    }
    Temperature_D_err {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_D_err";
        String fullnamepath "/Temperature_D_err";
    }
    TotH2OVap_D {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_D";
        String fullnamepath "/TotH2OVap_D";
    }
    H2O_MMR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_D_sdev";
        String fullnamepath "/H2O_MMR_D_sdev";
    }
    CoarseCloudPres_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_A_sdev";
        String fullnamepath "/CoarseCloudPres_TqJ_A_sdev";
    }
    CoarseCloudPres_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_A_min";
        String fullnamepath "/CoarseCloudPres_A_min";
    }
    EmisIR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_D_max";
        String fullnamepath "/EmisIR_D_max";
    }
    TropPres_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_A_max";
        String fullnamepath "/TropPres_A_max";
    }
    Temperature_MW_D_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_D_min";
        String fullnamepath "/Temperature_MW_D_min";
    }
    RelHum_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_D_max";
        String fullnamepath "/RelHum_D_max";
    }
    TotalCounts_MW_D {
        Int16 _FillValue 0;
        String origname "TotalCounts_MW_D";
        String fullnamepath "/TotalCounts_MW_D";
    }
    CH4_VMR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CH4_VMR_TqJ_A_ct";
        String fullnamepath "/CH4_VMR_TqJ_A_ct";
    }
    OLR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "OLR_D_min";
        String fullnamepath "/OLR_D_min";
    }
    CoarseCloudPres_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_D_sdev";
        String fullnamepath "/CoarseCloudPres_D_sdev";
    }
    RelHum_liquid_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_D_max";
        String fullnamepath "/RelHum_liquid_D_max";
    }
    CH4_VMR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_A";
        String fullnamepath "/CH4_VMR_TqJ_A";
    }
    SurfAirTemp_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_A_sdev";
        String fullnamepath "/SurfAirTemp_A_sdev";
    }
    RelHumSurf_D_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_D_ct";
        String fullnamepath "/RelHumSurf_D_ct";
    }
    CO_VMR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_D_min";
        String fullnamepath "/CO_VMR_D_min";
    }
    TotO3_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_A_min";
        String fullnamepath "/TotO3_TqJ_A_min";
    }
    RelHumSurf_liquid_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_D_sdev";
        String fullnamepath "/RelHumSurf_liquid_D_sdev";
    }
    SurfAirTemp_A_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_A_err";
        String fullnamepath "/SurfAirTemp_A_err";
    }
    CloudFrc_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_A_max";
        String fullnamepath "/CloudFrc_TqJ_A_max";
    }
    OLR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_D_sdev";
        String fullnamepath "/OLR_TqJ_D_sdev";
    }
    OLR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "OLR_D_sdev";
        String fullnamepath "/OLR_D_sdev";
    }
    SurfPres_Forecast_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_A_sdev";
        String fullnamepath "/SurfPres_Forecast_TqJ_A_sdev";
    }
    TotH2OVap_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_A_min";
        String fullnamepath "/TotH2OVap_A_min";
    }
    TotH2OVap_MW_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_D_min";
        String fullnamepath "/TotH2OVap_MW_D_min";
    }
    SurfAirTemp_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_D";
        String fullnamepath "/SurfAirTemp_D";
    }
    CoarseCloudFrc_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_A";
        String fullnamepath "/CoarseCloudFrc_A";
    }
    CoarseCloudPres_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_A_max";
        String fullnamepath "/CoarseCloudPres_A_max";
    }
    CloudTopPres_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CloudTopPres_TqJ_D_ct";
        String fullnamepath "/CloudTopPres_TqJ_D_ct";
    }
    RelHum_liquid_D_ct {
        Int16 _FillValue 0;
        String origname "RelHum_liquid_D_ct";
        String fullnamepath "/RelHum_liquid_D_ct";
    }
    OLR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_D_max";
        String fullnamepath "/OLR_TqJ_D_max";
    }
    H2O_MMR_Surf_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_A_sdev";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A_sdev";
    }
    TotCldLiqH2O_MW_A {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_A";
        String fullnamepath "/TotCldLiqH2O_MW_A";
    }
    TotH2OVap_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_D_sdev";
        String fullnamepath "/TotH2OVap_D_sdev";
    }
    CloudTopTemp_A_ct {
        Int16 _FillValue 0;
        String origname "CloudTopTemp_A_ct";
        String fullnamepath "/CloudTopTemp_A_ct";
    }
    CO_VMR_A_ct {
        Int16 _FillValue 0;
        String origname "CO_VMR_A_ct";
        String fullnamepath "/CO_VMR_A_ct";
    }
    FineCloudFrc_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_A_min";
        String fullnamepath "/FineCloudFrc_TqJ_A_min";
    }
    Temperature_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_A_err";
        String fullnamepath "/Temperature_TqJ_A_err";
    }
    OLR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_A_min";
        String fullnamepath "/OLR_TqJ_A_min";
    }
    CH4_VMR_D_ct {
        Int16 _FillValue 0;
        String origname "CH4_VMR_D_ct";
        String fullnamepath "/CH4_VMR_D_ct";
    }
    RelHum_liquid_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_A";
        String fullnamepath "/RelHum_liquid_A";
    }
    O3_VMR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_A_err";
        String fullnamepath "/O3_VMR_A_err";
    }
    TropTemp_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_A_sdev";
        String fullnamepath "/TropTemp_TqJ_A_sdev";
    }
    ClrOLR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_A_min";
        String fullnamepath "/ClrOLR_TqJ_A_min";
    }
    CloudFrc_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_D_min";
        String fullnamepath "/CloudFrc_D_min";
    }
    TotH2OVap_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_D_min";
        String fullnamepath "/TotH2OVap_TqJ_D_min";
    }
    CloudFrc_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_D_sdev";
        String fullnamepath "/CloudFrc_TqJ_D_sdev";
    }
    CoarseCloudFrc_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_A_min";
        String fullnamepath "/CoarseCloudFrc_TqJ_A_min";
    }
    FineCloudFrc_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "FineCloudFrc_TqJ_A_ct";
        String fullnamepath "/FineCloudFrc_TqJ_A_ct";
    }
    TotO3_A {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_A";
        String fullnamepath "/TotO3_A";
    }
    RelHum_liquid_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_D_min";
        String fullnamepath "/RelHum_liquid_D_min";
    }
    TropPres_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_A_sdev";
        String fullnamepath "/TropPres_A_sdev";
    }
    CoarseCloudPres_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_D_min";
        String fullnamepath "/CoarseCloudPres_TqJ_D_min";
    }
    TotH2OVap_A_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_A_ct";
        String fullnamepath "/TotH2OVap_A_ct";
    }
    TropTemp_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_A";
        String fullnamepath "/TropTemp_TqJ_A";
    }
    RelHum_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_A";
        String fullnamepath "/RelHum_TqJ_A";
    }
    RelHum_liquid_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_A_sdev";
        String fullnamepath "/RelHum_liquid_A_sdev";
    }
    GPHeight_A_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_A_ct";
        String fullnamepath "/GPHeight_A_ct";
    }
    SurfPres_Forecast_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_D";
        String fullnamepath "/SurfPres_Forecast_TqJ_D";
    }
    RelHum_liquid_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_A_min";
        String fullnamepath "/RelHum_liquid_A_min";
    }
    TropTemp_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_D_sdev";
        String fullnamepath "/TropTemp_TqJ_D_sdev";
    }
    TotO3_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_D_sdev";
        String fullnamepath "/TotO3_TqJ_D_sdev";
    }
    GPHeight_MW_A_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_MW_A_ct";
        String fullnamepath "/GPHeight_MW_A_ct";
    }
    TropPres_A_ct {
        Int16 _FillValue 0;
        String origname "TropPres_A_ct";
        String fullnamepath "/TropPres_A_ct";
    }
    EmisIR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_D_min";
        String fullnamepath "/EmisIR_D_min";
    }
    TotCH4_D_ct {
        Int16 _FillValue 0;
        String origname "TotCH4_D_ct";
        String fullnamepath "/TotCH4_D_ct";
    }
    SurfAirTemp_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_D_max";
        String fullnamepath "/SurfAirTemp_D_max";
    }
    CH4_VMR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_A_err";
        String fullnamepath "/CH4_VMR_A_err";
    }
    TropHeight_A_ct {
        Int16 _FillValue 0;
        String origname "TropHeight_A_ct";
        String fullnamepath "/TropHeight_A_ct";
    }
    SurfSkinTemp_A_ct {
        Int16 _FillValue 0;
        String origname "SurfSkinTemp_A_ct";
        String fullnamepath "/SurfSkinTemp_A_ct";
    }
    CoarseCloudFrc_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_A_sdev";
        String fullnamepath "/CoarseCloudFrc_A_sdev";
    }
    CloudTopTemp_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_A_max";
        String fullnamepath "/CloudTopTemp_A_max";
    }
    FineCloudFrc_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_D";
        String fullnamepath "/FineCloudFrc_TqJ_D";
    }
    H2O_MMR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_A_max";
        String fullnamepath "/H2O_MMR_A_max";
    }
    ClrOLR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_D_min";
        String fullnamepath "/ClrOLR_TqJ_D_min";
    }
    TotO3_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_A";
        String fullnamepath "/TotO3_TqJ_A";
    }
    H2O_MMR_Lyr_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Lyr_A_ct";
        String fullnamepath "/H2O_MMR_Lyr_A_ct";
    }
    CloudTopTemp_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_A";
        String fullnamepath "/CloudTopTemp_TqJ_A";
    }
    Emis_MW_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_D_sdev";
        String fullnamepath "/Emis_MW_D_sdev";
    }
    RelHumSurf_liquid_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_A_sdev";
        String fullnamepath "/RelHumSurf_liquid_TqJ_A_sdev";
    }
    CloudFrc_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CloudFrc_TqJ_A_ct";
        String fullnamepath "/CloudFrc_TqJ_A_ct";
    }
    OLR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "OLR_D_max";
        String fullnamepath "/OLR_D_max";
    }
    OLR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "OLR_TqJ_D_ct";
        String fullnamepath "/OLR_TqJ_D_ct";
    }
    RelHum_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_A_sdev";
        String fullnamepath "/RelHum_TqJ_A_sdev";
    }
    CO_VMR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_D_min";
        String fullnamepath "/CO_VMR_TqJ_D_min";
    }
    CloudTopPres_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_A_min";
        String fullnamepath "/CloudTopPres_A_min";
    }
    ClrOLR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "ClrOLR_TqJ_A_ct";
        String fullnamepath "/ClrOLR_TqJ_A_ct";
    }
    TropPres_A {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_A";
        String fullnamepath "/TropPres_A";
    }
    TotalCounts_D {
        Int16 _FillValue 0;
        String origname "TotalCounts_D";
        String fullnamepath "/TotalCounts_D";
    }
    RelHumSurf_liquid_A_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_liquid_A_ct";
        String fullnamepath "/RelHumSurf_liquid_A_ct";
    }
    H2O_MMR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_A_max";
        String fullnamepath "/H2O_MMR_TqJ_A_max";
    }
    TotCO_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_A_sdev";
        String fullnamepath "/TotCO_A_sdev";
    }
    ClrOLR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_D_sdev";
        String fullnamepath "/ClrOLR_D_sdev";
    }
    Temperature_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_A_sdev";
        String fullnamepath "/Temperature_TqJ_A_sdev";
    }
    H2O_MMR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_D_max";
        String fullnamepath "/H2O_MMR_D_max";
    }
    TotCO_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_D_sdev";
        String fullnamepath "/TotCO_TqJ_D_sdev";
    }
    SurfSkinTemp_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_A";
        String fullnamepath "/SurfSkinTemp_A";
    }
    SurfSkinTemp_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_D_sdev";
        String fullnamepath "/SurfSkinTemp_D_sdev";
    }
    H2O_MMR_Surf_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Surf_A_ct";
        String fullnamepath "/H2O_MMR_Surf_A_ct";
    }
    TropHeight_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_D_max";
        String fullnamepath "/TropHeight_D_max";
    }
    CoarseCloudTemp_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_A_min";
        String fullnamepath "/CoarseCloudTemp_TqJ_A_min";
    }
    TropTemp_A {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_A";
        String fullnamepath "/TropTemp_A";
    }
    TropHeight_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_A_sdev";
        String fullnamepath "/TropHeight_A_sdev";
    }
    TotCldLiqH2O_MW_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_A_max";
        String fullnamepath "/TotCldLiqH2O_MW_A_max";
    }
    TotCH4_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_D";
        String fullnamepath "/TotCH4_TqJ_D";
    }
    CloudFrc_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_A_min";
        String fullnamepath "/CloudFrc_A_min";
    }
    RelHum_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_A";
        String fullnamepath "/RelHum_A";
    }
    CloudTopTemp_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_D";
        String fullnamepath "/CloudTopTemp_D";
    }
    Temperature_D_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_D_max";
        String fullnamepath "/Temperature_D_max";
    }
    CloudTopPres_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_A_max";
        String fullnamepath "/CloudTopPres_A_max";
    }
    CoarseCloudTemp_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_A_min";
        String fullnamepath "/CoarseCloudTemp_A_min";
    }
    TropTemp_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TropTemp_TqJ_D_ct";
        String fullnamepath "/TropTemp_TqJ_D_ct";
    }
    Temperature_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_D_max";
        String fullnamepath "/Temperature_TqJ_D_max";
    }
    RelHumSurf_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_D_sdev";
        String fullnamepath "/RelHumSurf_D_sdev";
    }
    CloudFrc_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_A_min";
        String fullnamepath "/CloudFrc_TqJ_A_min";
    }
    TotCldLiqH2O_MW_D_ct {
        Int16 _FillValue 0;
        String origname "TotCldLiqH2O_MW_D_ct";
        String fullnamepath "/TotCldLiqH2O_MW_D_ct";
    }
    H2O_MMR_Surf_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_A";
        String fullnamepath "/H2O_MMR_Surf_A";
    }
    TropPres_D {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_D";
        String fullnamepath "/TropPres_D";
    }
    CoarseCloudFrc_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_D";
        String fullnamepath "/CoarseCloudFrc_D";
    }
    CoarseCloudFrc_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudFrc_TqJ_A_ct";
        String fullnamepath "/CoarseCloudFrc_TqJ_A_ct";
    }
    CloudFrc_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_D_err";
        String fullnamepath "/CloudFrc_D_err";
    }
    O3_VMR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_D_err";
        String fullnamepath "/O3_VMR_TqJ_D_err";
    }
    SurfSkinTemp_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_D_min";
        String fullnamepath "/SurfSkinTemp_D_min";
    }
    TotCO_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_A_min";
        String fullnamepath "/TotCO_TqJ_A_min";
    }
    H2O_MMR_Surf_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_A_min";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A_min";
    }
    TotCldLiqH2O_MW_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_D_min";
        String fullnamepath "/TotCldLiqH2O_MW_D_min";
    }
    H2O_MMR_Lyr_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_D_min";
        String fullnamepath "/H2O_MMR_Lyr_D_min";
    }
    CoarseCloudFrc_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_D_sdev";
        String fullnamepath "/CoarseCloudFrc_D_sdev";
    }
    RelHum_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_A_min";
        String fullnamepath "/RelHum_TqJ_A_min";
    }
    TotCO_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_A_min";
        String fullnamepath "/TotCO_A_min";
    }
    TotCO_D_ct {
        Int16 _FillValue 0;
        String origname "TotCO_D_ct";
        String fullnamepath "/TotCO_D_ct";
    }
    TropTemp_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TropTemp_TqJ_A_ct";
        String fullnamepath "/TropTemp_TqJ_A_ct";
    }
    CH4_VMR_D {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_D";
        String fullnamepath "/CH4_VMR_D";
    }
    RelHum_liquid_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_D_sdev";
        String fullnamepath "/RelHum_liquid_TqJ_D_sdev";
    }
    ClrOLR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "ClrOLR_TqJ_D_ct";
        String fullnamepath "/ClrOLR_TqJ_D_ct";
    }
    CoarseCloudTemp_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudTemp_TqJ_A_ct";
        String fullnamepath "/CoarseCloudTemp_TqJ_A_ct";
    }
    EmisIR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_A";
        String fullnamepath "/EmisIR_TqJ_A";
    }
    Emis_MW_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_A_sdev";
        String fullnamepath "/Emis_MW_A_sdev";
    }
    SurfSkinTemp_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_A_min";
        String fullnamepath "/SurfSkinTemp_TqJ_A_min";
    }
    H2O_MMR_Surf_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_D_sdev";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D_sdev";
    }
    H2O_MMR_Lyr_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Lyr_TqJ_D_ct";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D_ct";
    }
    TotCH4_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_D_sdev";
        String fullnamepath "/TotCH4_TqJ_D_sdev";
    }
    CloudFrc_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_A";
        String fullnamepath "/CloudFrc_A";
    }
    SurfPres_Forecast_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_A_min";
        String fullnamepath "/SurfPres_Forecast_TqJ_A_min";
    }
    RelHumSurf_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_D";
        String fullnamepath "/RelHumSurf_D";
    }
    TotCO_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_D_max";
        String fullnamepath "/TotCO_D_max";
    }
    EmisIR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_A_max";
        String fullnamepath "/EmisIR_TqJ_A_max";
    }
    EmisIR_D_ct {
        Int16 _FillValue 0;
        String origname "EmisIR_D_ct";
        String fullnamepath "/EmisIR_D_ct";
    }
    RelHum_liquid_A_ct {
        Int16 _FillValue 0;
        String origname "RelHum_liquid_A_ct";
        String fullnamepath "/RelHum_liquid_A_ct";
    }
    GPHeight_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_TqJ_D_ct";
        String fullnamepath "/GPHeight_TqJ_D_ct";
    }
    TropHeight_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_A_min";
        String fullnamepath "/TropHeight_A_min";
    }
    TotH2OVap_MW_D {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_D";
        String fullnamepath "/TotH2OVap_MW_D";
    }
    RelHumSurf_liquid_D_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_liquid_D_ct";
        String fullnamepath "/RelHumSurf_liquid_D_ct";
    }
    CO_VMR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CO_VMR_TqJ_A_ct";
        String fullnamepath "/CO_VMR_TqJ_A_ct";
    }
    CoarseCloudFrc_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_A_max";
        String fullnamepath "/CoarseCloudFrc_TqJ_A_max";
    }
    TotCH4_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_A_min";
        String fullnamepath "/TotCH4_A_min";
    }
    TropTemp_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_D_max";
        String fullnamepath "/TropTemp_D_max";
    }
    TotalCounts_TqJ_D {
        Int16 _FillValue 0;
        String origname "TotalCounts_TqJ_D";
        String fullnamepath "/TotalCounts_TqJ_D";
    }
    OLR_A_ct {
        Int16 _FillValue 0;
        String origname "OLR_A_ct";
        String fullnamepath "/OLR_A_ct";
    }
    CloudTopPres_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_A_sdev";
        String fullnamepath "/CloudTopPres_TqJ_A_sdev";
    }
    TropPres_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_D_min";
        String fullnamepath "/TropPres_TqJ_D_min";
    }
    H2O_MMR_Lyr_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_D";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D";
    }
    CoarseCloudTemp_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_A_max";
        String fullnamepath "/CoarseCloudTemp_A_max";
    }
    CoarseCloudPres_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudPres_A_ct";
        String fullnamepath "/CoarseCloudPres_A_ct";
    }
    RelHum_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_D_min";
        String fullnamepath "/RelHum_TqJ_D_min";
    }
    Temperature_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_D_min";
        String fullnamepath "/Temperature_TqJ_D_min";
    }
    CoarseCloudTemp_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudTemp_A_ct";
        String fullnamepath "/CoarseCloudTemp_A_ct";
    }
    ClrOLR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_A_sdev";
        String fullnamepath "/ClrOLR_A_sdev";
    }
    TropTemp_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_A_min";
        String fullnamepath "/TropTemp_TqJ_A_min";
    }
    TropHeight_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_A";
        String fullnamepath "/TropHeight_TqJ_A";
    }
    SurfSkinTemp_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_D_err";
        String fullnamepath "/SurfSkinTemp_TqJ_D_err";
    }
    O3_VMR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_D_max";
        String fullnamepath "/O3_VMR_TqJ_D_max";
    }
    ClrOLR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_A_err";
        String fullnamepath "/ClrOLR_TqJ_A_err";
    }
    CoarseCloudFrc_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_A";
        String fullnamepath "/CoarseCloudFrc_TqJ_A";
    }
    SurfPres_Forecast_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "SurfPres_Forecast_TqJ_A_ct";
        String fullnamepath "/SurfPres_Forecast_TqJ_A_ct";
    }
    SurfSkinTemp_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_D_max";
        String fullnamepath "/SurfSkinTemp_D_max";
    }
    FineCloudFrc_D_min {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_D_min";
        String fullnamepath "/FineCloudFrc_D_min";
    }
    OLR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "OLR_TqJ_A_ct";
        String fullnamepath "/OLR_TqJ_A_ct";
    }
    RelHum_liquid_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_A_max";
        String fullnamepath "/RelHum_liquid_TqJ_A_max";
    }
    RelHum_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_D_min";
        String fullnamepath "/RelHum_D_min";
    }
    CoarseCloudPres_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_A";
        String fullnamepath "/CoarseCloudPres_TqJ_A";
    }
    RelHum_D_ct {
        Int16 _FillValue 0;
        String origname "RelHum_D_ct";
        String fullnamepath "/RelHum_D_ct";
    }
    H2O_MMR_Lyr_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_D";
        String fullnamepath "/H2O_MMR_Lyr_D";
    }
    SurfAirTemp_D_ct {
        Int16 _FillValue 0;
        String origname "SurfAirTemp_D_ct";
        String fullnamepath "/SurfAirTemp_D_ct";
    }
    EmisIR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_D_max";
        String fullnamepath "/EmisIR_TqJ_D_max";
    }
    SurfAirTemp_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_A";
        String fullnamepath "/SurfAirTemp_A";
    }
    TotCldLiqH2O_MW_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_A_sdev";
        String fullnamepath "/TotCldLiqH2O_MW_A_sdev";
    }
    TotCO_A {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_A";
        String fullnamepath "/TotCO_A";
    }
    FineCloudFrc_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_D_max";
        String fullnamepath "/FineCloudFrc_TqJ_D_max";
    }
    CloudFrc_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_TqJ_A_sdev";
        String fullnamepath "/CloudFrc_TqJ_A_sdev";
    }
    TotO3_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_D_sdev";
        String fullnamepath "/TotO3_D_sdev";
    }
    RelHum_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_A_max";
        String fullnamepath "/RelHum_A_max";
    }
    H2O_MMR_Surf_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_A_err";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A_err";
    }
    CloudTopPres_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_A_sdev";
        String fullnamepath "/CloudTopPres_A_sdev";
    }
    FineCloudFrc_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_A";
        String fullnamepath "/FineCloudFrc_TqJ_A";
    }
    TotCO_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_A_max";
        String fullnamepath "/TotCO_A_max";
    }
    RelHum_liquid_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_D_min";
        String fullnamepath "/RelHum_liquid_TqJ_D_min";
    }
    CloudTopTemp_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_D_sdev";
        String fullnamepath "/CloudTopTemp_D_sdev";
    }
    RelHumSurf_liquid_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_A";
        String fullnamepath "/RelHumSurf_liquid_TqJ_A";
    }
    H2O_MMR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_A_err";
        String fullnamepath "/H2O_MMR_A_err";
    }
    CoarseCloudTemp_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_A_sdev";
        String fullnamepath "/CoarseCloudTemp_TqJ_A_sdev";
    }
    H2O_MMR_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_D";
        String fullnamepath "/H2O_MMR_D";
    }
    CloudFrc_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_A_err";
        String fullnamepath "/CloudFrc_A_err";
    }
    TotH2OVap_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_A_sdev";
        String fullnamepath "/TotH2OVap_TqJ_A_sdev";
    }
    GPHeight_MW_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_D_sdev";
        String fullnamepath "/GPHeight_MW_D_sdev";
    }
    CoarseCloudFrc_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudFrc_A_ct";
        String fullnamepath "/CoarseCloudFrc_A_ct";
    }
    CO_VMR_D_ct {
        Int16 _FillValue 0;
        String origname "CO_VMR_D_ct";
        String fullnamepath "/CO_VMR_D_ct";
    }
    H2O_MMR_Surf_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_D";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D";
    }
    OLR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "OLR_A_min";
        String fullnamepath "/OLR_A_min";
    }
    CloudFrc_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_D";
        String fullnamepath "/CloudFrc_D";
    }
    FineCloudFrc_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_D_sdev";
        String fullnamepath "/FineCloudFrc_TqJ_D_sdev";
    }
    TotCO_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TotCO_TqJ_D_ct";
        String fullnamepath "/TotCO_TqJ_D_ct";
    }
    TotH2OVap_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_A_max";
        String fullnamepath "/TotH2OVap_TqJ_A_max";
    }
    CoarseCloudPres_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_A_max";
        String fullnamepath "/CoarseCloudPres_TqJ_A_max";
    }
    TotH2OVap_MW_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_A_min";
        String fullnamepath "/TotH2OVap_MW_A_min";
    }
    H2O_MMR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_D_min";
        String fullnamepath "/H2O_MMR_D_min";
    }
    EmisIR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_A_err";
        String fullnamepath "/EmisIR_A_err";
    }
    GPHeight_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_A_max";
        String fullnamepath "/GPHeight_TqJ_A_max";
    }
    RelHum_liquid_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_D_sdev";
        String fullnamepath "/RelHum_liquid_D_sdev";
    }
    O3_VMR_A {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_A";
        String fullnamepath "/O3_VMR_A";
    }
    TotH2OVap_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_D";
        String fullnamepath "/TotH2OVap_TqJ_D";
    }
    CloudTopTemp_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_A_max";
        String fullnamepath "/CloudTopTemp_TqJ_A_max";
    }
    RelHumSurf_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_A";
        String fullnamepath "/RelHumSurf_A";
    }
    OLR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_A";
        String fullnamepath "/OLR_TqJ_A";
    }
    GPHeight_A_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_A_min";
        String fullnamepath "/GPHeight_A_min";
    }
    SurfSkinTemp_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "SurfSkinTemp_TqJ_A_ct";
        String fullnamepath "/SurfSkinTemp_TqJ_A_ct";
    }
    H2O_MMR_Lyr_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_D_max";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D_max";
    }
    SurfAirTemp_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_A_min";
        String fullnamepath "/SurfAirTemp_A_min";
    }
    CoarseCloudFrc_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_D_min";
        String fullnamepath "/CoarseCloudFrc_D_min";
    }
    TotCH4_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TotCH4_TqJ_A_ct";
        String fullnamepath "/TotCH4_TqJ_A_ct";
    }
    CoarseCloudTemp_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_A_sdev";
        String fullnamepath "/CoarseCloudTemp_A_sdev";
    }
    CloudTopPres_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_A_max";
        String fullnamepath "/CloudTopPres_TqJ_A_max";
    }
    TotH2OVap_MW_D_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_MW_D_ct";
        String fullnamepath "/TotH2OVap_MW_D_ct";
    }
    CO_VMR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_A_max";
        String fullnamepath "/CO_VMR_A_max";
    }
    TropHeight_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_A_max";
        String fullnamepath "/TropHeight_TqJ_A_max";
    }
    GPHeight_MW_D {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_D";
        String fullnamepath "/GPHeight_MW_D";
    }
    GPHeight_D {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_D";
        String fullnamepath "/GPHeight_D";
    }
    Temperature_MW_D_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_D_max";
        String fullnamepath "/Temperature_MW_D_max";
    }
    Temperature_D {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_D";
        String fullnamepath "/Temperature_D";
    }
    H2O_MMR_Surf_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_A_min";
        String fullnamepath "/H2O_MMR_Surf_A_min";
    }
    TropHeight_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_A_sdev";
        String fullnamepath "/TropHeight_TqJ_A_sdev";
    }
    CloudTopTemp_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_A_min";
        String fullnamepath "/CloudTopTemp_TqJ_A_min";
    }
    GPHeight_D_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_D_min";
        String fullnamepath "/GPHeight_D_min";
    }
    CloudTopTemp_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CloudTopTemp_TqJ_A_ct";
        String fullnamepath "/CloudTopTemp_TqJ_A_ct";
    }
    GPHeight_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_D_sdev";
        String fullnamepath "/GPHeight_TqJ_D_sdev";
    }
    TropHeight_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_D_max";
        String fullnamepath "/TropHeight_TqJ_D_max";
    }
    ClrOLR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_D_min";
        String fullnamepath "/ClrOLR_D_min";
    }
    CoarseCloudTemp_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_A";
        String fullnamepath "/CoarseCloudTemp_A";
    }
    H2O_MMR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_D_err";
        String fullnamepath "/H2O_MMR_D_err";
    }
    CoarseCloudPres_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudPres_TqJ_A_ct";
        String fullnamepath "/CoarseCloudPres_TqJ_A_ct";
    }
    H2O_MMR_Lyr_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_A_sdev";
        String fullnamepath "/H2O_MMR_Lyr_A_sdev";
    }
    CH4_VMR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_A_max";
        String fullnamepath "/CH4_VMR_TqJ_A_max";
    }
    TropTemp_A_ct {
        Int16 _FillValue 0;
        String origname "TropTemp_A_ct";
        String fullnamepath "/TropTemp_A_ct";
    }
    H2O_MMR_Lyr_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_D_min";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D_min";
    }
    TropTemp_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_D";
        String fullnamepath "/TropTemp_TqJ_D";
    }
    SurfPres_Forecast_A_ct {
        Int16 _FillValue 0;
        String origname "SurfPres_Forecast_A_ct";
        String fullnamepath "/SurfPres_Forecast_A_ct";
    }
    TropHeight_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_D";
        String fullnamepath "/TropHeight_TqJ_D";
    }
    LandSeaMask {
        Int16 _FillValue 0;
        String origname "LandSeaMask";
        String fullnamepath "/LandSeaMask";
    }
    CloudFrc_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_A_max";
        String fullnamepath "/CloudFrc_A_max";
    }
    TropTemp_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_TqJ_D_min";
        String fullnamepath "/TropTemp_TqJ_D_min";
    }
    H2O_MMR_Surf_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_D_sdev";
        String fullnamepath "/H2O_MMR_Surf_D_sdev";
    }
    CloudTopPres_D_ct {
        Int16 _FillValue 0;
        String origname "CloudTopPres_D_ct";
        String fullnamepath "/CloudTopPres_D_ct";
    }
    RelHumSurf_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_A_sdev";
        String fullnamepath "/RelHumSurf_TqJ_A_sdev";
    }
    CoarseCloudFrc_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_A_min";
        String fullnamepath "/CoarseCloudFrc_A_min";
    }
    GPHeight_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_TqJ_A_ct";
        String fullnamepath "/GPHeight_TqJ_A_ct";
    }
    GPHeight_MW_D_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_MW_D_ct";
        String fullnamepath "/GPHeight_MW_D_ct";
    }
    TropTemp_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_A_min";
        String fullnamepath "/TropTemp_A_min";
    }
    CloudTopTemp_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_D_err";
        String fullnamepath "/CloudTopTemp_D_err";
    }
    CoarseCloudTemp_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudTemp_TqJ_D_ct";
        String fullnamepath "/CoarseCloudTemp_TqJ_D_ct";
    }
    Temperature_MW_D {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_D";
        String fullnamepath "/Temperature_MW_D";
    }
    FineCloudFrc_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_D_sdev";
        String fullnamepath "/FineCloudFrc_D_sdev";
    }
    TotCO_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_D_min";
        String fullnamepath "/TotCO_D_min";
    }
    ClrOLR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_A_max";
        String fullnamepath "/ClrOLR_TqJ_A_max";
    }
    CoarseCloudPres_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_D";
        String fullnamepath "/CoarseCloudPres_TqJ_D";
    }
    RelHumSurf_A_ct {
        Int16 _FillValue 0;
        String origname "RelHumSurf_A_ct";
        String fullnamepath "/RelHumSurf_A_ct";
    }
    CoarseCloudPres_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_A_sdev";
        String fullnamepath "/CoarseCloudPres_A_sdev";
    }
    CoarseCloudPres_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudPres_D_ct";
        String fullnamepath "/CoarseCloudPres_D_ct";
    }
    H2O_MMR_Surf_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_D_max";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D_max";
    }
    TropPres_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_A";
        String fullnamepath "/TropPres_TqJ_A";
    }
    TotH2OVap_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_D_sdev";
        String fullnamepath "/TotH2OVap_TqJ_D_sdev";
    }
    RelHumSurf_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_D_min";
        String fullnamepath "/RelHumSurf_TqJ_D_min";
    }
    ClrOLR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_D_err";
        String fullnamepath "/ClrOLR_D_err";
    }
    GPHeight_D_ct {
        Int16 _FillValue 0;
        String origname "GPHeight_D_ct";
        String fullnamepath "/GPHeight_D_ct";
    }
    CoarseCloudPres_A {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_A";
        String fullnamepath "/CoarseCloudPres_A";
    }
    H2O_MMR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_A_err";
        String fullnamepath "/H2O_MMR_TqJ_A_err";
    }
    EmisIR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "EmisIR_TqJ_D_ct";
        String fullnamepath "/EmisIR_TqJ_D_ct";
    }
    TotCH4_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_A_max";
        String fullnamepath "/TotCH4_A_max";
    }
    Emis_MW_D_ct {
        Int16 _FillValue 0;
        String origname "Emis_MW_D_ct";
        String fullnamepath "/Emis_MW_D_ct";
    }
    H2O_MMR_Lyr_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_D_max";
        String fullnamepath "/H2O_MMR_Lyr_D_max";
    }
    CH4_VMR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_A_min";
        String fullnamepath "/CH4_VMR_TqJ_A_min";
    }
    TropHeight_D {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_D";
        String fullnamepath "/TropHeight_D";
    }
    TropPres_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_D_max";
        String fullnamepath "/TropPres_D_max";
    }
    Temperature_MW_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_A_sdev";
        String fullnamepath "/Temperature_MW_A_sdev";
    }
    RelHum_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_D";
        String fullnamepath "/RelHum_D";
    }
    EmisIR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_D";
        String fullnamepath "/EmisIR_TqJ_D";
    }
    EmisIR_A {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_A";
        String fullnamepath "/EmisIR_A";
    }
    O3_VMR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_A_min";
        String fullnamepath "/O3_VMR_TqJ_A_min";
    }
    TotO3_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_A_max";
        String fullnamepath "/TotO3_A_max";
    }
    ClrOLR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_D_max";
        String fullnamepath "/ClrOLR_D_max";
    }
    CO_VMR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_A_sdev";
        String fullnamepath "/CO_VMR_A_sdev";
    }
    CoarseCloudFrc_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_A_max";
        String fullnamepath "/CoarseCloudFrc_A_max";
    }
    Emis_MW_A {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_A";
        String fullnamepath "/Emis_MW_A";
    }
    RelHumSurf_liquid_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_D_max";
        String fullnamepath "/RelHumSurf_liquid_D_max";
    }
    GPHeight_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_A";
        String fullnamepath "/GPHeight_TqJ_A";
    }
    OLR_A {
        Float32 _FillValue -9999.000000;
        String origname "OLR_A";
        String fullnamepath "/OLR_A";
    }
    TropPres_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_A_sdev";
        String fullnamepath "/TropPres_TqJ_A_sdev";
    }
    TotalCounts_MW_A {
        Int16 _FillValue 0;
        String origname "TotalCounts_MW_A";
        String fullnamepath "/TotalCounts_MW_A";
    }
    CloudTopPres_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_D";
        String fullnamepath "/CloudTopPres_TqJ_D";
    }
    RelHumSurf_liquid_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_D";
        String fullnamepath "/RelHumSurf_liquid_TqJ_D";
    }
    TotCO_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_D";
        String fullnamepath "/TotCO_TqJ_D";
    }
    TotCO_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_D_sdev";
        String fullnamepath "/TotCO_D_sdev";
    }
    EmisIR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_D_sdev";
        String fullnamepath "/EmisIR_D_sdev";
    }
    H2O_MMR_Surf_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_TqJ_A_max";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A_max";
    }
    CO_VMR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_D_err";
        String fullnamepath "/CO_VMR_D_err";
    }
    H2O_MMR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_D_err";
        String fullnamepath "/H2O_MMR_TqJ_D_err";
    }
    SurfAirTemp_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_A";
        String fullnamepath "/SurfAirTemp_TqJ_A";
    }
    ClrOLR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_A_max";
        String fullnamepath "/ClrOLR_A_max";
    }
    RelHumSurf_liquid_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_A_max";
        String fullnamepath "/RelHumSurf_liquid_TqJ_A_max";
    }
    CoarseCloudTemp_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_D_sdev";
        String fullnamepath "/CoarseCloudTemp_D_sdev";
    }
    GPHeight_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_A_sdev";
        String fullnamepath "/GPHeight_TqJ_A_sdev";
    }
    H2O_MMR_Lyr_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_D_sdev";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_D_sdev";
    }
    H2O_MMR_Surf_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Surf_TqJ_D_ct";
        String fullnamepath "/H2O_MMR_Surf_TqJ_D_ct";
    }
    RelHumSurf_liquid_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_D";
        String fullnamepath "/RelHumSurf_liquid_D";
    }
    SurfAirTemp_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_D_sdev";
        String fullnamepath "/SurfAirTemp_D_sdev";
    }
    CloudTopPres_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_A";
        String fullnamepath "/CloudTopPres_TqJ_A";
    }
    RelHumSurf_liquid_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_A_min";
        String fullnamepath "/RelHumSurf_liquid_TqJ_A_min";
    }
    TotH2OVap_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_A_min";
        String fullnamepath "/TotH2OVap_TqJ_A_min";
    }
    TotH2OVap_MW_A {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_A";
        String fullnamepath "/TotH2OVap_MW_A";
    }
    SurfAirTemp_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_D";
        String fullnamepath "/SurfAirTemp_TqJ_D";
    }
    RelHum_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "RelHum_TqJ_D_ct";
        String fullnamepath "/RelHum_TqJ_D_ct";
    }
    TotCO_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_A";
        String fullnamepath "/TotCO_TqJ_A";
    }
    SurfSkinTemp_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_D";
        String fullnamepath "/SurfSkinTemp_D";
    }
    CoarseCloudPres_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_D_max";
        String fullnamepath "/CoarseCloudPres_D_max";
    }
    H2O_MMR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_A_min";
        String fullnamepath "/H2O_MMR_A_min";
    }
    ClrOLR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_D";
        String fullnamepath "/ClrOLR_TqJ_D";
    }
    CoarseCloudFrc_D_ct {
        Int16 _FillValue 0;
        String origname "CoarseCloudFrc_D_ct";
        String fullnamepath "/CoarseCloudFrc_D_ct";
    }
    RelHum_liquid_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_A";
        String fullnamepath "/RelHum_liquid_TqJ_A";
    }
    CH4_VMR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_A_err";
        String fullnamepath "/CH4_VMR_TqJ_A_err";
    }
    CoarseCloudTemp_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_D_max";
        String fullnamepath "/CoarseCloudTemp_D_max";
    }
    RelHumSurf_liquid_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_A_min";
        String fullnamepath "/RelHumSurf_liquid_A_min";
    }
    RelHumSurf_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_A_min";
        String fullnamepath "/RelHumSurf_TqJ_A_min";
    }
    TotCO_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_A_max";
        String fullnamepath "/TotCO_TqJ_A_max";
    }
    Temperature_MW_A_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_A_min";
        String fullnamepath "/Temperature_MW_A_min";
    }
    RelHumSurf_liquid_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_D_min";
        String fullnamepath "/RelHumSurf_liquid_D_min";
    }
    Temperature_MW_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_D_sdev";
        String fullnamepath "/Temperature_MW_D_sdev";
    }
    TotCH4_D {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_D";
        String fullnamepath "/TotCH4_D";
    }
    EmisIR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_D_min";
        String fullnamepath "/EmisIR_TqJ_D_min";
    }
    TotCH4_A {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_A";
        String fullnamepath "/TotCH4_A";
    }
    RelHum_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_D";
        String fullnamepath "/RelHum_TqJ_D";
    }
    H2O_MMR_Lyr_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_A_err";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A_err";
    }
    SurfAirTemp_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_A_min";
        String fullnamepath "/SurfAirTemp_TqJ_A_min";
    }
    CH4_VMR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_A_min";
        String fullnamepath "/CH4_VMR_A_min";
    }
    TropTemp_D {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_D";
        String fullnamepath "/TropTemp_D";
    }
    CloudFrc_D_ct {
        Int16 _FillValue 0;
        String origname "CloudFrc_D_ct";
        String fullnamepath "/CloudFrc_D_ct";
    }
    GPHeight_MW_A_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_A_min";
        String fullnamepath "/GPHeight_MW_A_min";
    }
    CO_VMR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_A";
        String fullnamepath "/CO_VMR_TqJ_A";
    }
    TotO3_D_ct {
        Int16 _FillValue 0;
        String origname "TotO3_D_ct";
        String fullnamepath "/TotO3_D_ct";
    }
    TotO3_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TotO3_TqJ_A_ct";
        String fullnamepath "/TotO3_TqJ_A_ct";
    }
    Temperature_A {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_A";
        String fullnamepath "/Temperature_A";
    }
    GPHeight_MW_D_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_D_max";
        String fullnamepath "/GPHeight_MW_D_max";
    }
    ClrOLR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_D_err";
        String fullnamepath "/ClrOLR_TqJ_D_err";
    }
    CloudTopTemp_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_D_sdev";
        String fullnamepath "/CloudTopTemp_TqJ_D_sdev";
    }
    Temperature_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_D_sdev";
        String fullnamepath "/Temperature_D_sdev";
    }
    OLR_D_ct {
        Int16 _FillValue 0;
        String origname "OLR_D_ct";
        String fullnamepath "/OLR_D_ct";
    }
    Temperature_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_A_sdev";
        String fullnamepath "/Temperature_A_sdev";
    }
    SurfSkinTemp_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_A_max";
        String fullnamepath "/SurfSkinTemp_TqJ_A_max";
    }
    TotH2OVap_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_TqJ_D_max";
        String fullnamepath "/TotH2OVap_TqJ_D_max";
    }
    ClrOLR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_D_max";
        String fullnamepath "/ClrOLR_TqJ_D_max";
    }
    RelHum_liquid_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "RelHum_liquid_TqJ_D_ct";
        String fullnamepath "/RelHum_liquid_TqJ_D_ct";
    }
    O3_VMR_D_ct {
        Int16 _FillValue 0;
        String origname "O3_VMR_D_ct";
        String fullnamepath "/O3_VMR_D_ct";
    }
    Temperature_A_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_A_min";
        String fullnamepath "/Temperature_A_min";
    }
    TropHeight_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_TqJ_D_sdev";
        String fullnamepath "/TropHeight_TqJ_D_sdev";
    }
    TotCO_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCO_TqJ_D_min";
        String fullnamepath "/TotCO_TqJ_D_min";
    }
    Emis_MW_D_max {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_D_max";
        String fullnamepath "/Emis_MW_D_max";
    }
    EmisIR_D {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_D";
        String fullnamepath "/EmisIR_D";
    }
    CoarseCloudPres_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_D_max";
        String fullnamepath "/CoarseCloudPres_TqJ_D_max";
    }
    FineCloudFrc_A_ct {
        Int16 _FillValue 0;
        String origname "FineCloudFrc_A_ct";
        String fullnamepath "/FineCloudFrc_A_ct";
    }
    RelHum_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_TqJ_D_sdev";
        String fullnamepath "/RelHum_TqJ_D_sdev";
    }
    SurfPres_Forecast_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_A_max";
        String fullnamepath "/SurfPres_Forecast_A_max";
    }
    GPHeight_D_max {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_D_max";
        String fullnamepath "/GPHeight_D_max";
    }
    TotH2OVap_A {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_A";
        String fullnamepath "/TotH2OVap_A";
    }
    EmisIR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_A_min";
        String fullnamepath "/EmisIR_A_min";
    }
    TotO3_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_D_min";
        String fullnamepath "/TotO3_TqJ_D_min";
    }
    SurfSkinTemp_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_A_sdev";
        String fullnamepath "/SurfSkinTemp_TqJ_A_sdev";
    }
    TropHeight_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TropHeight_TqJ_A_ct";
        String fullnamepath "/TropHeight_TqJ_A_ct";
    }
    SurfSkinTemp_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_A_max";
        String fullnamepath "/SurfSkinTemp_A_max";
    }
    CloudTopPres_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_D_max";
        String fullnamepath "/CloudTopPres_TqJ_D_max";
    }
    CoarseCloudTemp_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_D_min";
        String fullnamepath "/CoarseCloudTemp_D_min";
    }
    CO_VMR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_D_err";
        String fullnamepath "/CO_VMR_TqJ_D_err";
    }
    TotO3_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_A_min";
        String fullnamepath "/TotO3_A_min";
    }
    CH4_VMR_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_D_min";
        String fullnamepath "/CH4_VMR_D_min";
    }
    Temperature_D_min {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_D_min";
        String fullnamepath "/Temperature_D_min";
    }
    TropHeight_A {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_A";
        String fullnamepath "/TropHeight_A";
    }
    SurfPres_Forecast_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "SurfPres_Forecast_TqJ_D_ct";
        String fullnamepath "/SurfPres_Forecast_TqJ_D_ct";
    }
    CH4_VMR_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_D_max";
        String fullnamepath "/CH4_VMR_D_max";
    }
    TotO3_D_err {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_D_err";
        String fullnamepath "/TotO3_D_err";
    }
    CH4_VMR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_A_sdev";
        String fullnamepath "/CH4_VMR_A_sdev";
    }
    Temperature_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_TqJ_A_max";
        String fullnamepath "/Temperature_TqJ_A_max";
    }
    TotH2OVap_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_D_max";
        String fullnamepath "/TotH2OVap_D_max";
    }
    CO_VMR_A {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_A";
        String fullnamepath "/CO_VMR_A";
    }
    H2O_MMR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_TqJ_D_ct";
        String fullnamepath "/H2O_MMR_TqJ_D_ct";
    }
    ClrOLR_A_ct {
        Int16 _FillValue 0;
        String origname "ClrOLR_A_ct";
        String fullnamepath "/ClrOLR_A_ct";
    }
    TotCldLiqH2O_MW_D_err {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_D_err";
        String fullnamepath "/TotCldLiqH2O_MW_D_err";
    }
    EmisIR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_A_max";
        String fullnamepath "/EmisIR_A_max";
    }
    H2O_MMR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_D_max";
        String fullnamepath "/H2O_MMR_TqJ_D_max";
    }
    RelHumSurf_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_A";
        String fullnamepath "/RelHumSurf_TqJ_A";
    }
    OLR_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_A_max";
        String fullnamepath "/OLR_TqJ_A_max";
    }
    Temperature_MW_A_ct {
        Int16 _FillValue 0;
        String origname "Temperature_MW_A_ct";
        String fullnamepath "/Temperature_MW_A_ct";
    }
    CloudTopTemp_A {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_A";
        String fullnamepath "/CloudTopTemp_A";
    }
    CH4_VMR_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_D_sdev";
        String fullnamepath "/CH4_VMR_D_sdev";
    }
    TotCldLiqH2O_MW_D {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_D";
        String fullnamepath "/TotCldLiqH2O_MW_D";
    }
    CO_VMR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_A_err";
        String fullnamepath "/CO_VMR_TqJ_A_err";
    }
    CloudTopPres_A_ct {
        Int16 _FillValue 0;
        String origname "CloudTopPres_A_ct";
        String fullnamepath "/CloudTopPres_A_ct";
    }
    RelHum_liquid_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_A_min";
        String fullnamepath "/RelHum_liquid_TqJ_A_min";
    }
    H2O_MMR_Lyr_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_A";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A";
    }
    H2O_MMR_Lyr_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Lyr_D_ct";
        String fullnamepath "/H2O_MMR_Lyr_D_ct";
    }
    CloudFrc_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_D_max";
        String fullnamepath "/CloudFrc_D_max";
    }
    CH4_VMR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_D_err";
        String fullnamepath "/CH4_VMR_TqJ_D_err";
    }
    TotO3_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TotO3_TqJ_D_ct";
        String fullnamepath "/TotO3_TqJ_D_ct";
    }
    H2O_MMR_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_A_sdev";
        String fullnamepath "/H2O_MMR_A_sdev";
    }
    RelHum_liquid_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_TqJ_A_sdev";
        String fullnamepath "/RelHum_liquid_TqJ_A_sdev";
    }
    SurfSkinTemp_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_TqJ_D_min";
        String fullnamepath "/SurfSkinTemp_TqJ_D_min";
    }
    SurfAirTemp_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_A_max";
        String fullnamepath "/SurfAirTemp_TqJ_A_max";
    }
    SurfPres_Forecast_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_D_max";
        String fullnamepath "/SurfPres_Forecast_D_max";
    }
    GPHeight_A {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_A";
        String fullnamepath "/GPHeight_A";
    }
    EmisIR_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "EmisIR_TqJ_A_ct";
        String fullnamepath "/EmisIR_TqJ_A_ct";
    }
    O3_VMR_A_max {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_A_max";
        String fullnamepath "/O3_VMR_A_max";
    }
    RelHumSurf_D_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_D_min";
        String fullnamepath "/RelHumSurf_D_min";
    }
    OLR_A_err {
        Float32 _FillValue -9999.000000;
        String origname "OLR_A_err";
        String fullnamepath "/OLR_A_err";
    }
    SurfPres_Forecast_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_D_min";
        String fullnamepath "/SurfPres_Forecast_D_min";
    }
    RelHumSurf_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_D_sdev";
        String fullnamepath "/RelHumSurf_TqJ_D_sdev";
    }
    H2O_MMR_Lyr_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_A_max";
        String fullnamepath "/H2O_MMR_Lyr_A_max";
    }
    CoarseCloudFrc_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_D_sdev";
        String fullnamepath "/CoarseCloudFrc_TqJ_D_sdev";
    }
    CoarseCloudFrc_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_D_max";
        String fullnamepath "/CoarseCloudFrc_D_max";
    }
    TotH2OVap_MW_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_D_sdev";
        String fullnamepath "/TotH2OVap_MW_D_sdev";
    }
    TotO3_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_A_max";
        String fullnamepath "/TotO3_TqJ_A_max";
    }
    CH4_VMR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_TqJ_A_sdev";
        String fullnamepath "/CH4_VMR_TqJ_A_sdev";
    }
    TropTemp_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropTemp_A_max";
        String fullnamepath "/TropTemp_A_max";
    }
    CloudTopTemp_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_D_max";
        String fullnamepath "/CloudTopTemp_D_max";
    }
    TropPres_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_A_min";
        String fullnamepath "/TropPres_TqJ_A_min";
    }
    TropPres_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_D_max";
        String fullnamepath "/TropPres_TqJ_D_max";
    }
    EmisIR_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "EmisIR_TqJ_A_err";
        String fullnamepath "/EmisIR_TqJ_A_err";
    }
    TropHeight_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_D_sdev";
        String fullnamepath "/TropHeight_D_sdev";
    }
    RelHumSurf_liquid_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_A_sdev";
        String fullnamepath "/RelHumSurf_liquid_A_sdev";
    }
    RelHumSurf_liquid_A {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_A";
        String fullnamepath "/RelHumSurf_liquid_A";
    }
    TotO3_A_err {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_A_err";
        String fullnamepath "/TotO3_A_err";
    }
    CO_VMR_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_D_max";
        String fullnamepath "/CO_VMR_TqJ_D_max";
    }
    FineCloudFrc_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_D_min";
        String fullnamepath "/FineCloudFrc_TqJ_D_min";
    }
    CloudTopPres_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_TqJ_D_err";
        String fullnamepath "/CloudTopPres_TqJ_D_err";
    }
    TotO3_TqJ_A_err {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_TqJ_A_err";
        String fullnamepath "/TotO3_TqJ_A_err";
    }
    ClrOLR_D_ct {
        Int16 _FillValue 0;
        String origname "ClrOLR_D_ct";
        String fullnamepath "/ClrOLR_D_ct";
    }
    SurfPres_Forecast_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_A";
        String fullnamepath "/SurfPres_Forecast_TqJ_A";
    }
    CoarseCloudPres_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_TqJ_A_min";
        String fullnamepath "/CoarseCloudPres_TqJ_A_min";
    }
    GPHeight_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_TqJ_A_min";
        String fullnamepath "/GPHeight_TqJ_A_min";
    }
    CoarseCloudTemp_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_D";
        String fullnamepath "/CoarseCloudTemp_TqJ_D";
    }
    RelHum_liquid_D {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_liquid_D";
        String fullnamepath "/RelHum_liquid_D";
    }
    SurfAirTemp_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "SurfAirTemp_TqJ_A_ct";
        String fullnamepath "/SurfAirTemp_TqJ_A_ct";
    }
    H2O_MMR_Surf_A_max {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_A_max";
        String fullnamepath "/H2O_MMR_Surf_A_max";
    }
    H2O_MMR_Lyr_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_A_sdev";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A_sdev";
    }
    TotO3_A_ct {
        Int16 _FillValue 0;
        String origname "TotO3_A_ct";
        String fullnamepath "/TotO3_A_ct";
    }
    Temperature_MW_A_max {
        Float32 _FillValue -9999.000000;
        String origname "Temperature_MW_A_max";
        String fullnamepath "/Temperature_MW_A_max";
    }
    TotH2OVap_MW_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_D_max";
        String fullnamepath "/TotH2OVap_MW_D_max";
    }
    GPHeight_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_A_sdev";
        String fullnamepath "/GPHeight_A_sdev";
    }
    SurfAirTemp_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_TqJ_D_min";
        String fullnamepath "/SurfAirTemp_TqJ_D_min";
    }
    SurfSkinTemp_D_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_D_err";
        String fullnamepath "/SurfSkinTemp_D_err";
    }
    Emis_MW_A_max {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_A_max";
        String fullnamepath "/Emis_MW_A_max";
    }
    H2O_MMR_Lyr_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_D_err";
        String fullnamepath "/H2O_MMR_Lyr_D_err";
    }
    TropPres_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "TropPres_TqJ_A_ct";
        String fullnamepath "/TropPres_TqJ_A_ct";
    }
    OLR_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_D_err";
        String fullnamepath "/OLR_TqJ_D_err";
    }
    Emis_MW_A_min {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_A_min";
        String fullnamepath "/Emis_MW_A_min";
    }
    TropHeight_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TropHeight_A_max";
        String fullnamepath "/TropHeight_A_max";
    }
    FineCloudFrc_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "FineCloudFrc_TqJ_D_ct";
        String fullnamepath "/FineCloudFrc_TqJ_D_ct";
    }
    H2O_MMR_Lyr_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_TqJ_A_min";
        String fullnamepath "/H2O_MMR_Lyr_TqJ_A_min";
    }
    CoarseCloudFrc_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudFrc_TqJ_D_max";
        String fullnamepath "/CoarseCloudFrc_TqJ_D_max";
    }
    RelHumSurf_liquid_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_TqJ_D_sdev";
        String fullnamepath "/RelHumSurf_liquid_TqJ_D_sdev";
    }
    CoarseCloudTemp_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_D_min";
        String fullnamepath "/CoarseCloudTemp_TqJ_D_min";
    }
    H2O_MMR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_D_min";
        String fullnamepath "/H2O_MMR_TqJ_D_min";
    }
    TotH2OVap_D_err {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_D_err";
        String fullnamepath "/TotH2OVap_D_err";
    }
    H2O_MMR_Lyr_A {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_A";
        String fullnamepath "/H2O_MMR_Lyr_A";
    }
    H2O_MMR_Surf_TqJ_A_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Surf_TqJ_A_ct";
        String fullnamepath "/H2O_MMR_Surf_TqJ_A_ct";
    }
    H2O_MMR_Surf_D_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Surf_D_err";
        String fullnamepath "/H2O_MMR_Surf_D_err";
    }
    GPHeight_MW_A {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_MW_A";
        String fullnamepath "/GPHeight_MW_A";
    }
    SurfPres_Forecast_D {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_D";
        String fullnamepath "/SurfPres_Forecast_D";
    }
    SurfPres_Forecast_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_D_max";
        String fullnamepath "/SurfPres_Forecast_TqJ_D_max";
    }
    CloudFrc_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudFrc_D_sdev";
        String fullnamepath "/CloudFrc_D_sdev";
    }
    ClrOLR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_TqJ_A_sdev";
        String fullnamepath "/ClrOLR_TqJ_A_sdev";
    }
    O3_VMR_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_D_min";
        String fullnamepath "/O3_VMR_TqJ_D_min";
    }
    TotO3_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_D_max";
        String fullnamepath "/TotO3_D_max";
    }
    TotO3_D_min {
        Float32 _FillValue -9999.000000;
        String origname "TotO3_D_min";
        String fullnamepath "/TotO3_D_min";
    }
    RelHumSurf_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_TqJ_D_max";
        String fullnamepath "/RelHumSurf_TqJ_D_max";
    }
    TotCH4_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_D_max";
        String fullnamepath "/TotCH4_TqJ_D_max";
    }
    RelHumSurf_liquid_A_max {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_liquid_A_max";
        String fullnamepath "/RelHumSurf_liquid_A_max";
    }
    SurfPres_Forecast_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_A_min";
        String fullnamepath "/SurfPres_Forecast_A_min";
    }
    CoarseCloudTemp_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_D_max";
        String fullnamepath "/CoarseCloudTemp_TqJ_D_max";
    }
    TotCH4_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_A";
        String fullnamepath "/TotCH4_TqJ_A";
    }
    CH4_VMR_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CH4_VMR_D_err";
        String fullnamepath "/CH4_VMR_D_err";
    }
    RelHumSurf_A_min {
        Float32 _FillValue -9999.000000;
        String origname "RelHumSurf_A_min";
        String fullnamepath "/RelHumSurf_A_min";
    }
    CO_VMR_TqJ_D {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_D";
        String fullnamepath "/CO_VMR_TqJ_D";
    }
    SurfPres_Forecast_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_A_max";
        String fullnamepath "/SurfPres_Forecast_TqJ_A_max";
    }
    GPHeight_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "GPHeight_D_sdev";
        String fullnamepath "/GPHeight_D_sdev";
    }
    CloudTopTemp_TqJ_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_D_max";
        String fullnamepath "/CloudTopTemp_TqJ_D_max";
    }
    CoarseCloudPres_D_min {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudPres_D_min";
        String fullnamepath "/CoarseCloudPres_D_min";
    }
    SurfSkinTemp_A_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfSkinTemp_A_min";
        String fullnamepath "/SurfSkinTemp_A_min";
    }
    FineCloudFrc_D {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_D";
        String fullnamepath "/FineCloudFrc_D";
    }
    RelHum_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_D_sdev";
        String fullnamepath "/RelHum_D_sdev";
    }
    TotH2OVap_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "TotH2OVap_TqJ_D_ct";
        String fullnamepath "/TotH2OVap_TqJ_D_ct";
    }
    O3_VMR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_D_sdev";
        String fullnamepath "/O3_VMR_TqJ_D_sdev";
    }
    CloudTopTemp_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_A_sdev";
        String fullnamepath "/CloudTopTemp_A_sdev";
    }
    H2O_MMR_Surf_D_ct {
        Int16 _FillValue 0;
        String origname "H2O_MMR_Surf_D_ct";
        String fullnamepath "/H2O_MMR_Surf_D_ct";
    }
    SurfAirTemp_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "SurfAirTemp_TqJ_D_ct";
        String fullnamepath "/SurfAirTemp_TqJ_D_ct";
    }
    SurfPres_Forecast_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_D_sdev";
        String fullnamepath "/SurfPres_Forecast_D_sdev";
    }
    Emis_MW_D_min {
        Float32 _FillValue -9999.000000;
        String origname "Emis_MW_D_min";
        String fullnamepath "/Emis_MW_D_min";
    }
    CoarseCloudTemp_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_D_sdev";
        String fullnamepath "/CoarseCloudTemp_TqJ_D_sdev";
    }
    OLR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "OLR_TqJ_A_sdev";
        String fullnamepath "/OLR_TqJ_A_sdev";
    }
    ClrOLR_A_min {
        Float32 _FillValue -9999.000000;
        String origname "ClrOLR_A_min";
        String fullnamepath "/ClrOLR_A_min";
    }
    SurfPres_Forecast_TqJ_D_min {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_TqJ_D_min";
        String fullnamepath "/SurfPres_Forecast_TqJ_D_min";
    }
    TotH2OVap_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_A_max";
        String fullnamepath "/TotH2OVap_A_max";
    }
    TotCH4_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "TotCH4_TqJ_A_min";
        String fullnamepath "/TotCH4_TqJ_A_min";
    }
    CloudTopTemp_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_A_min";
        String fullnamepath "/CloudTopTemp_A_min";
    }
    TotCldLiqH2O_MW_A_ct {
        Int16 _FillValue 0;
        String origname "TotCldLiqH2O_MW_A_ct";
        String fullnamepath "/TotCldLiqH2O_MW_A_ct";
    }
    FineCloudFrc_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "FineCloudFrc_TqJ_A_max";
        String fullnamepath "/FineCloudFrc_TqJ_A_max";
    }
    OLR_D {
        Float32 _FillValue -9999.000000;
        String origname "OLR_D";
        String fullnamepath "/OLR_D";
    }
    CO_VMR_TqJ_A_min {
        Float32 _FillValue -9999.000000;
        String origname "CO_VMR_TqJ_A_min";
        String fullnamepath "/CO_VMR_TqJ_A_min";
    }
    TotCldLiqH2O_MW_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TotCldLiqH2O_MW_D_sdev";
        String fullnamepath "/TotCldLiqH2O_MW_D_sdev";
    }
    H2O_MMR_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_TqJ_D_sdev";
        String fullnamepath "/H2O_MMR_TqJ_D_sdev";
    }
    Temperature_D_ct {
        Int16 _FillValue 0;
        String origname "Temperature_D_ct";
        String fullnamepath "/Temperature_D_ct";
    }
    TropPres_TqJ_D_sdev {
        Float32 _FillValue -9999.000000;
        String origname "TropPres_TqJ_D_sdev";
        String fullnamepath "/TropPres_TqJ_D_sdev";
    }
    CloudFrc_A_ct {
        Int16 _FillValue 0;
        String origname "CloudFrc_A_ct";
        String fullnamepath "/CloudFrc_A_ct";
    }
    CloudTopTemp_TqJ_D_err {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopTemp_TqJ_D_err";
        String fullnamepath "/CloudTopTemp_TqJ_D_err";
    }
    Topography {
        Float32 _FillValue -9999.000000;
        String origname "Topography";
        String fullnamepath "/Topography";
    }
    CH4_VMR_A_ct {
        Int16 _FillValue 0;
        String origname "CH4_VMR_A_ct";
        String fullnamepath "/CH4_VMR_A_ct";
    }
    CloudTopPres_D_max {
        Float32 _FillValue -9999.000000;
        String origname "CloudTopPres_D_max";
        String fullnamepath "/CloudTopPres_D_max";
    }
    RelHum_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "RelHum_A_sdev";
        String fullnamepath "/RelHum_A_sdev";
    }
    O3_VMR_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "O3_VMR_TqJ_D_ct";
        String fullnamepath "/O3_VMR_TqJ_D_ct";
    }
    TotH2OVap_MW_A_max {
        Float32 _FillValue -9999.000000;
        String origname "TotH2OVap_MW_A_max";
        String fullnamepath "/TotH2OVap_MW_A_max";
    }
    O3_VMR_TqJ_A {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_A";
        String fullnamepath "/O3_VMR_TqJ_A";
    }
    O3_VMR_TqJ_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "O3_VMR_TqJ_A_sdev";
        String fullnamepath "/O3_VMR_TqJ_A_sdev";
    }
    TotCO_A_ct {
        Int16 _FillValue 0;
        String origname "TotCO_A_ct";
        String fullnamepath "/TotCO_A_ct";
    }
    SurfAirTemp_D_err {
        Float32 _FillValue -9999.000000;
        String origname "SurfAirTemp_D_err";
        String fullnamepath "/SurfAirTemp_D_err";
    }
    CloudTopTemp_TqJ_D_ct {
        Int16 _FillValue 0;
        String origname "CloudTopTemp_TqJ_D_ct";
        String fullnamepath "/CloudTopTemp_TqJ_D_ct";
    }
    SurfPres_Forecast_A_sdev {
        Float32 _FillValue -9999.000000;
        String origname "SurfPres_Forecast_A_sdev";
        String fullnamepath "/SurfPres_Forecast_A_sdev";
    }
    H2O_MMR_Lyr_A_err {
        Float32 _FillValue -9999.000000;
        String origname "H2O_MMR_Lyr_A_err";
        String fullnamepath "/H2O_MMR_Lyr_A_err";
    }
    CoarseCloudTemp_TqJ_A_max {
        Float32 _FillValue -9999.000000;
        String origname "CoarseCloudTemp_TqJ_A_max";
        String fullnamepath "/CoarseCloudTemp_TqJ_A_max";
    }
    CoarseCloudLayer {
        String long_name "Mid-layer pressure";
        String units "hPa";
        String format "F7.2";
        String origname "CoarseCloudLayer";
        String fullnamepath "/CoarseCloudLayer";
    }
    EmisFreqIR {
        String long_name "Wavenumber";
        String units "cm^-1";
        String format "F5.1";
        String origname "EmisFreqIR";
        String fullnamepath "/EmisFreqIR";
    }
    EmisFreqMW {
        String long_name "Frequency";
        String units "GHz";
        String format "F5.1";
        String origname "EmisFreqMW";
        String fullnamepath "/EmisFreqMW";
    }
    FineCloudLayer {
        String long_name "Mid-layer pressure";
        String units "hPa";
        String format "F7.2";
        String origname "FineCloudLayer";
        String fullnamepath "/FineCloudLayer";
    }
    H2OPressureLay {
        String long_name "Mid-layer Pressure";
        String units "hPa";
        String format "F7.2";
        String origname "H2OPressureLay";
        String fullnamepath "/H2OPressureLay";
    }
    H2OPressureLev {
        String long_name "Pressure";
        String units "hPa";
        String format "F7.2";
        String origname "H2OPressureLev";
        String fullnamepath "/H2OPressureLev";
    }
    Latitude {
        String long_name "Latitude";
        String units "degrees_north";
        String format "F5.1";
        String origname "Latitude";
        String fullnamepath "/Latitude";
    }
    Longitude {
        String long_name "Longitude";
        String units "degrees_east";
        String format "F6.1";
        String origname "Longitude";
        String fullnamepath "/Longitude";
    }
    StdPressureLev {
        String long_name "Pressure";
        String units "hPa";
        String format "F7.2";
        String origname "StdPressureLev";
        String fullnamepath "/StdPressureLev";
    }
    HDF5_GLOBAL {
        String HDFEOSVersion "HDFEOS_V2.18";
        String StructMetadata_0 "GROUP=SwathStructure
END_GROUP=SwathStructure
";
    }
}
