Attributes {
    b1 {
    }
    c1 {
    }
    i8 {
    }
    ui8 {
    }
    i16 {
    }
    ui16 {
    }
    i32 {
    }
    ui32 {
    }
    f32 {
    }
    f64 {
    }
    s {
    }
    u {
    }
    e {
        d4:enum_def {
            Byte red 1;
            Byte green 2;
            Byte blue 3;
        }
    }
    dropped_dap4_vars {
        var_0 {
            String type "Int64";
            String name "i64";
        }
        var_1 {
            String type "UInt64";
            String name "ui64";
        }
        var_2 {
            String type "Opaque";
            String name "o";
        }
    }
}
