# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Log: test.13.exp,v $
# Revision 1.1  1994/12/21 17:01:29  jimg
# Added these to the testsuite.
#

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.13

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Status from parser: 0
DDS failed semantic check
DDS failed full semantic check
Dataset {
    Int32 i;
} ;
parse error, expecting \`\'=\'\' line: 5
A dataset must have a name
A dataset must have a name"

dds-test_start p $srcdir$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


