#
# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Id: test.17.exp,v 1.2 2000/09/22 02:52:59 jimg Exp $

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.17

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Status from parser: 0
Error parsing the text on line 8 at or near: Map
In the dataset descriptor object: Expected a variable declaration
(e.g., Int32 i;). Make sure that the variable name is not the name
of a datatype and that the Array: and Maps: sections of a Grid are
labeled properly.
"

dds-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.17.exp,v $
# Revision 1.2  2000/09/22 02:52:59  jimg
# Fixes to the tests to recognize some of the new error messages. Also,
# the test drivers were modified to catch the exceptions now thrown by
# some of the parsers.
#
# Revision 1.1  2000/08/16 18:30:22  jimg
# Added tests for dots in variable names and fancier error messages
#

