# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Log: test.13.exp,v $
# Revision 1.5  1998/08/13 22:09:36  jimg
# Fixed test after fixing misspelled error message.
#
# Revision 1.4  1997/03/27 18:20:08  jimg
# Update for version 2.13
#
# Revision 1.3  1996/08/13 16:38:16  jimg
# Fixed tests so that they match the output of the parser.
#
# Revision 1.2  1996/05/14 15:41:37  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.1  1994/12/21  17:01:29  jimg
# Added these to the testsuite.
#

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.13

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Status from parser: 0
DDS failed semantic check
DDS failed full semantic check
Dataset {
    Int32 i;
} ;
In the dataset descriptor object:
Expected an array subscript.

A dataset must have a name
A dataset must have a name"

dds-test_start p $srcdir$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


