# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Log: test.14.exp,v $
# Revision 1.1  1994/12/21 17:01:31  jimg
# Added these to the testsuite.
#

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.14

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Status from parser: 1
DDS past semantic check
DDS past full semantic check
Dataset {
} data5;"

dds-test_start p $srcdir$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


