# expect/tcl code to test the dds parser and scanner
# jhrg
#
# $Log: test.3.exp,v $
# Revision 1.2  1996/05/14 15:41:42  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.1  1994/12/21  17:01:33  jimg
# Added these to the testsuite.
#

global comp_output		# contains output from dds-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.3

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Status from parser: 1
DDS past semantic check
DDS past full semantic check
Dataset {
    Int32 i\[10\];
    Float64 f\[20\];
} data3;"

dds-test_start p $srcdir$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


