
# expect/tcl code to test the das scanner
# jhrg
#
# $Log: scanner.5.exp,v $
# Revision 1.1  1996/07/16 16:54:36  jimg
# Added.
#
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

set test_name scanner.5

set prompt "das-test:"
set timeout 2
set pass 1

das-test_start s

expect {
    "${prompt} " { 
    }
    timeout { 
	send_user "Timeout\n"
	set pass 0
    }
}

if {$pass} {
    set thing "byte\r\n"
    send $thing

    expect {
	-re ".*BYTE\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    set thing "Byte\r\n"
    send $thing

    expect {
	-re ".*BYTE\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    set thing "BYTE\r\n"
    send $thing

    expect {
	-re ".*BYTE\r\n${prompt} $" { 
	}
	timeout { 
	    send_user "Timeout\n"
	    set pass 0
	}
    }
}

if {$pass} {
    pass $test_name
} else {
    fail $test_name
}

das-test_exit
