# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.20.exp,v $
# Revision 1.5  2000/04/07 00:20:36  jimg
# Fixed expresion tests.
#
# Revision 1.4  1999/04/29 00:05:39  jimg
# *** empty log message ***
#
# Revision 1.6  1997/05/13 23:29:18  jimg
# *** empty log message ***
#
# Revision 1.5  1997/03/27 18:19:58  jimg
# Update for version 2.13
#
# Revision 1.4  1996/11/13 19:23:44  jimg
# *** empty log message ***
#
# Revision 1.3  1996/08/12 22:22:18  jimg
# Changed for the new error message text from the parser.
#
# Revision 1.2  1996/04/05 22:00:13  jimg
# Misc Changes for release 2.0.1 of the core software - for developers.
#
# Revision 1.1  1995/02/16  15:34:52  jimg
# Added these tests. See comments in files in parent directory.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.20

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    test {
        Int32 x 70000;
    }
}
Parse error (line: 8):
`80000' is not a 16-bit integer value value.
It must be between -32768 and 32767.
`80000' is not an Int16 value.
parse() returned: 0"

das-test_start p $srcdir$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
