# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.6.exp,v $
# Revision 1.6  1996/08/12 22:22:20  jimg
# Changed for the new error message text from the parser.
#
# Revision 1.5  1996/05/14 15:40:53  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.4  1995/02/10  03:31:16  jimg
# Modified test cases for type checking.
#
# Revision 1.3  1994/12/09  21:45:51  jimg
# Modified for new unix.exp.
#
# Revision 1.2  1994/09/09  16:15:26  jimg
# Fixed namign of the test (was given as $srcdir/$test_name, should have been
# $srcdir$test_name).
#
# Revision 1.1  1994/08/29  19:57:24  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.6

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: $srcdir$test_name
Attributes {
    var_11 {
        string slota val1;
        string slotb val2;
    }
}
Error parsing the text on line 7:
Expected an attribute type (Byte, Int32, 
Float64, String or Url) followed by a name and value.
parse() returned: 0"

das-test_start p $srcdir$test_name -

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


