# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.1.exp,v $
# Revision 1.4  1994/10/05 16:51:45  jimg
# Added TYPE to each of the DAS test files.
# The `expect' files correcly check for that in the output.
#
# Revision 1.3  1994/09/27  23:14:13  jimg
# Changed expected outcomes to match new das.print() mfunc.
#
# Revision 1.2  1994/09/09  16:15:20  jimg
# Fixed namign of the test (was given as $srcdir/$test_name, should have been
# $srcdir$test_name).
#
# Revision 1.1  1994/08/29  19:57:19  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.1

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: $srcdir$test_name
Attributes {
    var1 {
        string name bob;
        string type human;
        int32 age 19;
    }
    var2 {
        string name joe;
        string type dog;
        int32 age 8;
    }
    var3 {
        int32 size large;
        string color red;
        string type art;
    }
    var4 {
    }
    var5 {
        string height 5.0in.;
        string units inches;
        float64 max 5.0;
        string weight 100lbs;
        string color red;
    }
}"

das-test_start $srcdir$test_name -

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


