# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.13.exp,v $
# Revision 1.8  2000/06/16 18:15:01  jimg
# Merged with 3.1.7
#
# Revision 1.7.10.1  2000/06/15 02:24:56  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.7  1999/03/24 23:42:22  jimg
# Added or updated for the new simple types (Int16, UInt16 and Float32)
#
# Revision 1.6  1997/05/13 23:29:13  jimg
# *** empty log message ***
#
# Revision 1.5  1997/03/27 18:19:54  jimg
# Update for version 2.13
#
# Revision 1.4  1996/11/13 19:23:41  jimg
# *** empty log message ***
#
# Revision 1.3  1996/08/12 22:22:15  jimg
# Changed for the new error message text from the parser.
#
# Revision 1.2  1996/05/14 15:40:44  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.1  1995/02/16  15:34:48  jimg
# Added these tests. See comments in files in parent directory.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.13

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    var1 {
    }
}
Expected an attribute type (Byte, Int16, UInt16, Int32, UInt32, Float32,
Float64, String or Url) followed by a name and value.
parse() returned: 0"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
