# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.7.exp,v $
# Revision 1.2  1996/05/14 15:40:54  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.1  1995/02/16  15:34:53  jimg
# Added these tests. See comments in files in parent directory.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.7

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: $srcdir$test_name
Attributes {
    aa {
        int32 i 10;
        float64 f 12.9;
        string test test;
    }
}
parse error line: 10
parse() returned: 0"

das-test_start p $srcdir$test_name -

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


