# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.3.exp,v $
# Revision 1.2  1994/09/09 16:15:22  jimg
# Fixed namign of the test (was given as $srcdir/$test_name, should have been
# $srcdir$test_name).
#
# Revision 1.1  1994/08/29  19:57:21  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.3

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: $srcdir$test_name
Attributes {
var1{
quote1 \"\\\"\";
quote2 \"\\7 seven\";
comment \"One thing about these long comments is that they might cause
problems with memory - overwrites, ...\";
comment2 \"This quote test a \\\"quote within a quote\\\", he said\";
}
}"

das-test_start $srcdir$test_name -

# send_user "comp output: $comp_output\n"
# send_user "test out: $test_out\n"

# send_user "result of compare [string compare $test_out $comp_output]\n"
# send_user "result of match [string match $test_out $comp_output]\n"

if ![string compare $test_out $comp_output] {
    pass "$test_name"
} else {
    fail "$test_name"
}


