# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.20.exp,v $
# Revision 1.1  1997/01/28 18:17:52  jimg
# *** empty log message ***
#
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.20

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: das-testsuite/test.20
Attributes {
    var11 {
        string value1 m/s;
        String value2 \"miles/hour\";
    }
}"

das-test_start p $srcdir$test_name -

if ![string compare $test_out $comp_output] {
    pass "$test_name"
} else {
    fail "$test_name"
}
