# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.5.exp,v $
# Revision 1.1  1994/08/29 19:57:23  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.5

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: ./test-inputs//test.5
Unterminated quote (starts on line 6)
"

das-test_start $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


