# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.4.exp,v $
# Revision 1.8  1996/08/12 22:22:19  jimg
# Changed for the new error message text from the parser.
#
# Revision 1.7  1996/05/14 15:40:51  jimg
# These changes have already been checked in once before. However, I
# corrupted the source repository and restored it from a 5/9/96 backup
# tape. The previous version's log entry should cover the changes.
#
# Revision 1.6  1994/12/09  21:45:48  jimg
# Modified for new unix.exp.
#
# Revision 1.5  1994/10/13  16:04:12  jimg
# Now works with the new das-test (but only when das-test is compiled
# w/o DEBUG and TRACE_NEW).
#
# Revision 1.4  1994/10/05  16:51:50  jimg
# Added TYPE to each of the DAS test files.
# The `expect' files correcly check for that in the output.
#
# Revision 1.3  1994/09/27  23:14:16  jimg
# Changed expected outcomes to match new das.print() mfunc.
#
# Revision 1.2  1994/09/09  16:15:23  jimg
# Fixed namign of the test (was given as $srcdir/$test_name, should have been
# $srcdir$test_name).
#
# Revision 1.1  1994/08/29  19:57:22  jimg
# Test procedures for the DAS parser, scanner and C++ class.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.4

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Reading from: $srcdir$test_name
Attributes {
    a {
        string b c;
    }
}
Error parsing the text on line 5:
Expected an attribute type (Byte, Int32, 
Float64, String or Url) followed by a name and value.
parse() returned: 0"

das-test_start p $srcdir$test_name -

# send_user "comp output: $comp_output\n"
# send_user "test out: $test_out\n"

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


