
# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.23.exp,v $
# Revision 1.2  2001/01/26 19:48:10  jimg
# Merged with release-3-2-3.
#
# Revision 1.1.2.1  2000/11/30 05:20:19  jimg
# Added
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.23

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    var1 {
        Int32 x 14;
        Int32 y 15, 16, 17;
    }
    Alias var2 var1;
}"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
