
# expect/tcl code to test the das parser and scanner
# jhrg
#
# $Log: test.32.exp,v $
# Revision 1.2  2002/06/03 22:21:16  jimg
# Merged with release-3-2-9
#
# Revision 1.1.2.1  2002/03/14 20:01:16  jimg
# Added
#
# Revision 1.1.2.1  2000/11/30 05:20:20  jimg
# Added
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_name' is the name of the das input file for this test.

set test_name test.32

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Attributes {
    var1 {
        Float64 g 6.02e23;
        Float64 h NaN;
        Float32 i NaN;
    }
}"

das-test_start p $srcdir/$test_name

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}
