
# Tcl/Expect code for the getdap test. This really is designed to test the
# various servers (hdf, dsp, netcdf, matlab, ...) on serveral different
# platforms. 
# 
# $Id$

# Make sure the global var GETDAP is set correctly.

global GETDAP
if ![info exists GETDAP] then {
    set GETDAP [transform ./getdap]
}

# The four `required' procs are _start, _load, _exit and _version.

proc getdap_start { {switches ""} {urls ""} {file ""}} {
    global verbose
    global GETDAP
    global comp_output
    global spawn_id

    if ![string compare $file ""] {
	if {$verbose >= 1} {
	    send_user "Testing getdap $switches $urls ...\n"
	    exp_internal 1
	}
	catch "exec $GETDAP $switches $urls" comp_output
    } else {
	if {$verbose >= 1} {
	    send_user "Testing getdap $switches $urls >& $file ...\n"
	    exp_internal 1
	}
	catch "exec $GETDAP $switches $urls > $file" comp_output
    }
}

proc getdap_load {} {
}

proc getdap_exit {} {
    # send -raw ""
}

proc getdap_version {} {
    send_user "grid test suite 1.0\n"
}




