Attributes {
    u {
        String units "meter per second";
        String long_name "UWind";
    }
    v {
        String units "meter per second";
        String long_name "VWind";
    }
    lat {
        String units "degree North";
	String long_name "Latitude";
    }
    lon {
        String units "degree East";
	String long_name "Longitude";
    }
    time {
    }
    NC_GLOBAL {
    }
    DODS_EXTRA {
    }
}
