
# expect/tcl code to test the expression parser and scanner. This test checks
# to see that the expr parser correctly rejects arrays that are partially
# constrained. 6/11/2002 jhrg

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.ya
set test_file test.c

# The variable test_equation is the equation to test.

set test_equation {"i,f,a" -b}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Sequence {
        Int32 i;
        Int32 j;
        Sequence {
            Float32 f;
            Float32 g;
            Sequence {
                Byte a;
                Byte b;
            } baby;
        } child;
    } parent;
} testc;
The data:
Sequence {
    Int32 i;
    Sequence {
        Float32 f;
        Sequence {
            Byte a;
        } baby;
    } child;
} parent = { { 32, { { 0.01, { { 0 }, { 1 }, { 2 }, { 3 } } }, { 1.00998, { { 4 }, { 5 }, { 6 }, { 7 } } }, { 84.6923, { { 8 }, { 9 }, { 10 }, { 11 } } }, { 13.0431, { { 12 }, { 13 }, { 14 }, { 15 } } } } }, { 1024, { { 45.897, { { 16 }, { 17 }, { 18 }, { 19 } } }, { 94.1542, { { 20 }, { 21 }, { 22 }, { 23 } } }, { -9.33074, { { 24 }, { 25 }, { 26 }, { 27 } } }, { -9.37994, { { 28 }, { 29 }, { 30 }, { 31 } } } } }, { 32768, { { -4.47181, { { 32 }, { 33 }, { 34 }, { 35 } } }, { 97.1301, { { 36 }, { 37 }, { 38 }, { 39 } } }, { 25.6459, { { 40 }, { 41 }, { 42 }, { 43 } } }, { 49.0991, { { 44 }, { 45 }, { 46 }, { 47 } } } } }, { 1048576, { { -91.9246, { { 48 }, { 49 }, { 50 }, { 51 } } }, { 73.0156, { { 52 }, { 53 }, { 54 }, { 55 } } }, { -68.8086, { { 56 }, { 57 }, { 58 }, { 59 } } }, { 30.1734, { { 60 }, { 61 }, { 62 }, { 63 } } } } } };"

expr-test_start p ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}

# $Log: test.ya.exp,v $
# Revision 1.2  2005/01/28 17:25:13  jimg
# Resolved conflicts from merge with release-3-4-9
#
# Revision 1.1.2.1  2005/01/19 18:26:31  jimg
# Added
#