
# expect/tcl code to test the expression parser and scanner
# jhrg
#
# $Log: test.g.exp,v $
# Revision 1.2  1997/06/05 22:52:33  jimg
# *** empty log message ***
#
# Revision 1.1  1996/11/27 21:06:22  jimg
# Expect this test to fail because of problems passing double quotes through
# Tcl/Expect.
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.g
set test_file test.4

# The variable test_equation is the equation to test.

set test_equation {s&s=~"Very Silly.*"}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "Dataset {
    Int32 i\\\[20\\\];
    String s;
    Int32 j;
    List Int32 l;
} test1;
The data:"

expr-test_start p ${srcdir}${test_file} ${test_equation}

if ![string compare $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    xfail "$test_name"
}


