
# expect/tcl code to test the expression parser and scanner
# jhrg
#
# $Log: test.q.exp,v $
# Revision 1.1  1999/03/24 23:42:24  jimg
# Added or updated for the new simple types (Int16, UInt16 and Float32)
#
# Revision 1.4  1998/03/27 04:28:52  jimg
# Fixed tests for the new DDS::send() mime header stuff
#
# Revision 1.3  1997/06/05 22:52:38  jimg
# *** empty log message ***
#
# Revision 1.2  1997/03/27 18:20:14  jimg
# Update for version 2.13
#
# Revision 1.1  1996/11/27 22:52:49  jimg
# *** empty log message ***
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.q
set test_file test.7

# The variable test_equation is the equation to test.

set test_equation {x,y,f}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int16 x;
    UInt16 y;
    Float32 f;
} data5;
The data:
Int16 x = 32000;
UInt16 y = 64000;
Float32 f = 99.999;"

expr-test_start p ${srcdir}${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


