
# expect/tcl code to test the expression parser and scanner
# jhrg
#
# $Log: test.a.exp,v $
# Revision 1.1  1997/06/05 22:53:29  jimg
# *** empty log message ***
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.a
set test_file test.2

# The variable test_equation is the equation to test.

set test_equation s1

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Structure {
        Int32 j;
        Int32 k;
    } s1;
    Structure {
        Int32 l;
        Int32 m;
    } s2\\\[10\\\];
    Structure {
        Int32 n;
        Int32 o;
    } s3;
} test2;
HTTP/1.0 200 OK
Server: DODS/*
Content-type: application/octet-stream
Content-Description: dods_data

The data:
Structure {
    Int32 j;
    Int32 k;
} s1 = { 123456789, 123456789 };"

expr-test_start p ${srcdir}${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


