
# expect/tcl code to test the expression parser and scanner
# jhrg
#
# $Log: test.f.exp,v $
# Revision 1.7  2003/05/16 00:18:35  jimg
# Tests changed because List has been removed from the DAP.
#
# Revision 1.6  2000/10/03 22:18:04  jimg
# Fixes to the tests to accomodate debugging fixes in DDS.cc
#
# Revision 1.5  2000/09/22 02:53:00  jimg
# Fixes to the tests to recognize some of the new error messages. Also,
# the test drivers were modified to catch the exceptions now thrown by
# some of the parsers.
#
# Revision 1.4  2000/06/16 18:15:02  jimg
# Merged with 3.1.7
#
# Revision 1.3.20.1  2000/06/15 02:24:58  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.3  1998/09/10 19:17:59  jehamby
# Change Str::print_val() to quote Strings when printing them (so geturl can
# generate less ambiguous output).
#
# Revision 1.2  1998/03/27 04:28:50  jimg
# Fixed tests for the new DDS::send() mime header stuff
#
# Revision 1.1  1997/06/05 22:53:35  jimg
# *** empty log message ***
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.f
set test_file test.4

# The variable test_equation is the equation to test.

set test_equation {s & s =~ "^Silly.*"}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int32 i\\\[20\\\];
    String s;
    Int32 j;
} test1;
The data:
String s = \"Silly test string: one, two, ...\";"

expr-test_start p ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


