
# expect/tcl code to test the expression parser and scanner
# jhrg
#
# $Log: test.k.exp,v $
# Revision 1.7  2000/10/03 22:18:04  jimg
# Fixes to the tests to accomodate debugging fixes in DDS.cc
#
# Revision 1.6  2000/09/22 02:53:00  jimg
# Fixes to the tests to recognize some of the new error messages. Also,
# the test drivers were modified to catch the exceptions now thrown by
# some of the parsers.
#
# Revision 1.5  2000/06/16 18:15:02  jimg
# Merged with 3.1.7
#
# Revision 1.4.28.1  2000/06/15 02:24:58  jimg
# Fixed the tests: problems with PATH, etc. broke the tests on my new machine
#
# Revision 1.4  1998/03/27 04:28:52  jimg
# Fixed tests for the new DDS::send() mime header stuff
#
# Revision 1.3  1997/06/05 22:52:38  jimg
# *** empty log message ***
#
# Revision 1.2  1997/03/27 18:20:14  jimg
# Update for version 2.13
#
# Revision 1.1  1996/11/27 22:52:49  jimg
# *** empty log message ***
#

global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The variable `test_file' is the name of the das input file for this test.

set test_name test.k
set test_file test.6

# The variable test_equation is the equation to test.

set test_equation {i\[1:2\]\[2:4\]}

# The variable `test_out' is a string that contains the text that should be
# stored in comp_output by das-test_start. The two strings should match
# exactly.

set test_out "The complete DDS:
Dataset {
    Int32 i\\\[20\\\]\\\[10\\\];
    String s;
} test1;
The data:
Int32 i\\\[2\\\]\\\[3\\\] = {{123456789, 123456789, 123456789},{123456789, 123456789, 123456789}};"

expr-test_start p ${srcdir}/${test_file} ${test_equation}

if [string match $test_out $comp_output] { # check comp_output
    pass "$test_name"
} else {
    fail "$test_name"
}


