# This is the source distribution package build

name: source distribution

on:
  push:
    branches: [ feature/test-buildout ]
  # pull_request:
  #   branches: [ master ]
  # workflow_dispatch:

jobs:
    source-distribution:
        runs-on: ubuntu-16.04

        steps: 
          - name: Checkout repo
            uses: actions/checkout@v2

          - name: Installs
            run: |
              set -x
              sudo apt-get update
              sudo apt-get --yes install libxml2-dev uuid-dev libcurl4-openssl-dev libcppunit-dev gcovr build-essential lintian fakeroot

          - name: cache-bison
            id: bison-src-dist  # Used below in the 'if'. So i changed the id to match the if statement below
            uses: actions/cache@v2
            with:
              path: $prefix/deps
              key: sd-pkg           #changed the key to avoid conflict with the id.

      # build the depdendencies so that we don't have to update teh container
      # every time the deps change.

          - name: build bison dependency
            if: steps.bison-src-dist.outputs.cache-hit != 'true'   #this statement should carry cache step id not the key, inform James & Nathan
            run: |
              git clone https://github.com/OPENDAP/hyrax-dependencies
              cd hyrax-dependencies
              make --jobs=$jobs bison

          - name: Configure
            run: |
              set -x
              autoreconf -i

          - name: Build source distro package
            run: |
              set -x
              #export LIBDAP_BUILD=srcdist
              sudo mkdir -p GHACTIONS_BUILD_DIR/package
              #pwd
              ./configure --prefix=$prefix --enable-developer
              make dist -j7 --jobs=$jobs
              # sudo cp libdap-*.tar.gz $GHACTIONS_BUILD_DIR/package
              # sudo cp libdap-*.tar.gz $GHACTIONS_BUILD_DIR/package/libdap-snapshot.tar.gz;

        # Make both a libdap-<version> and libdap-snapshot tar.gz. This will simplify
        # other operations that use the libdap source code like the bes build.

